Param(
	[string] [Parameter(Mandatory=$true)] $Repository	
)
[String]$pattern = "[^a-zA-Z1-9.-]"
[String]$project = "$env:SYSTEM_TEAMPROJECT"
[String]$projecturi = "$env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI"
[String]$BuildNumber="$env:BUILD_BUILDNUMBER"
[String]$Commit="$env:BUILD_SOURCEVERSION"
[String]$TagName=[string]::Format("{0}-{1}-{2}",$env:RELEASE_DEFINITIONNAME,$env:RELEASE_ENVIRONMENTNAME,$BuildNumber)
$TagName=$TagName -replace $pattern,""

$headers = @{ Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN" }

Write-Host "Calling Azure Devops Rest Endpoint" 
$url=[string]::Format("{0}/{1}/_apis/git/repositories/{2}/refs?filter=tags/{3}&api-version=5.0",$projecturi,$project,$Repository,$TagName)
$response=$null
$response = Invoke-RestMethod -Uri $url -ContentType "application/json; charset=utf-8" -headers $headers -Method GET
if($null -ne $response -and $response.count -gt 0){
    Write-Host "Tag already exists. Exiting."
    return
}

 
$url=[string]::Format("{0}/{1}/_apis/git/repositories/{2}/annotatedtags?api-version=5.1-preview.1",$projecturi,$project,$Repository)
$body="{`"name`":`"$TagName`",`"objectId`":null,`"taggedObject`":{`"objectId`":`"$Commit`",`"objectType`":`"commit`"},`"taggedBy`":null,`"message`":`"Generated By Release Pipeline:$env:RELEASE_DEFINITIONNAME for Stage:$env:RELEASE_ENVIRONMENTNAME and Build Number: $BuildNumber`"}"

Write-Host $body
 
$response= Invoke-RestMethod -Uri $url  -ContentType "application/json; charset=utf-8" -Body $body -headers $headers -Method POST
 
Write-Host $response