declare namespace Web {
  interface Contact_Base extends WebEntity {
    accountrolecode?: contact_accountrolecode | null;
    address1_addressid?: string | null;
    address1_addresstypecode?: contact_address1_addresstypecode | null;
    address1_city?: string | null;
    address1_composite?: string | null;
    address1_country?: string | null;
    address1_county?: string | null;
    address1_fax?: string | null;
    address1_freighttermscode?: contact_address1_freighttermscode | null;
    address1_latitude?: number | null;
    address1_line1?: string | null;
    address1_line2?: string | null;
    address1_line3?: string | null;
    address1_longitude?: number | null;
    address1_name?: string | null;
    address1_postalcode?: string | null;
    address1_postofficebox?: string | null;
    address1_primarycontactname?: string | null;
    address1_shippingmethodcode?: contact_address1_shippingmethodcode | null;
    address1_stateorprovince?: string | null;
    address1_telephone1?: string | null;
    address1_telephone2?: string | null;
    address1_telephone3?: string | null;
    address1_upszone?: string | null;
    address1_utcoffset?: number | null;
    address2_addressid?: string | null;
    address2_addresstypecode?: contact_address2_addresstypecode | null;
    address2_city?: string | null;
    address2_composite?: string | null;
    address2_country?: string | null;
    address2_county?: string | null;
    address2_fax?: string | null;
    address2_freighttermscode?: contact_address2_freighttermscode | null;
    address2_latitude?: number | null;
    address2_line1?: string | null;
    address2_line2?: string | null;
    address2_line3?: string | null;
    address2_longitude?: number | null;
    address2_name?: string | null;
    address2_postalcode?: string | null;
    address2_postofficebox?: string | null;
    address2_primarycontactname?: string | null;
    address2_shippingmethodcode?: contact_address2_shippingmethodcode | null;
    address2_stateorprovince?: string | null;
    address2_telephone1?: string | null;
    address2_telephone2?: string | null;
    address2_telephone3?: string | null;
    address2_upszone?: string | null;
    address2_utcoffset?: number | null;
    address3_addressid?: string | null;
    address3_addresstypecode?: contact_address3_addresstypecode | null;
    address3_city?: string | null;
    address3_composite?: string | null;
    address3_country?: string | null;
    address3_county?: string | null;
    address3_fax?: string | null;
    address3_freighttermscode?: contact_address3_freighttermscode | null;
    address3_latitude?: number | null;
    address3_line1?: string | null;
    address3_line2?: string | null;
    address3_line3?: string | null;
    address3_longitude?: number | null;
    address3_name?: string | null;
    address3_postalcode?: string | null;
    address3_postofficebox?: string | null;
    address3_primarycontactname?: string | null;
    address3_shippingmethodcode?: contact_address3_shippingmethodcode | null;
    address3_stateorprovince?: string | null;
    address3_telephone1?: string | null;
    address3_telephone2?: string | null;
    address3_telephone3?: string | null;
    address3_upszone?: string | null;
    address3_utcoffset?: number | null;
    adx_confirmremovepassword?: boolean | null;
    adx_createdbyipaddress?: string | null;
    adx_createdbyusername?: string | null;
    adx_identity_accessfailedcount?: number | null;
    adx_identity_emailaddress1confirmed?: boolean | null;
    adx_identity_lastsuccessfullogin?: Date | null;
    adx_identity_locallogindisabled?: boolean | null;
    adx_identity_lockoutenabled?: boolean | null;
    adx_identity_lockoutenddate?: Date | null;
    adx_identity_logonenabled?: boolean | null;
    adx_identity_mobilephoneconfirmed?: boolean | null;
    adx_identity_newpassword?: string | null;
    adx_identity_passwordhash?: string | null;
    adx_identity_securitystamp?: string | null;
    adx_identity_twofactorenabled?: boolean | null;
    adx_identity_username?: string | null;
    adx_modifiedbyipaddress?: string | null;
    adx_modifiedbyusername?: string | null;
    adx_organizationname?: string | null;
    adx_profilealert?: boolean | null;
    adx_profilealertdate?: Date | null;
    adx_profilealertinstructions?: string | null;
    adx_profileisanonymous?: boolean | null;
    adx_profilelastactivity?: Date | null;
    adx_profilemodifiedon?: Date | null;
    adx_publicprofilecopy?: string | null;
    adx_timezone?: number | null;
    aging30?: number | null;
    aging30_base?: number | null;
    aging60?: number | null;
    aging60_base?: number | null;
    aging90?: number | null;
    aging90_base?: number | null;
    anniversary?: Date | null;
    annualincome?: number | null;
    annualincome_base?: number | null;
    assistantname?: string | null;
    assistantphone?: string | null;
    birthdate?: Date | null;
    business2?: string | null;
    callback?: string | null;
    childrensnames?: string | null;
    company?: string | null;
    contactid?: string | null;
    createdon?: Date | null;
    creditlimit?: number | null;
    creditlimit_base?: number | null;
    creditonhold?: boolean | null;
    customersizecode?: contact_customersizecode | null;
    customertypecode?: contact_customertypecode | null;
    department?: string | null;
    description?: string | null;
    donotbulkemail?: boolean | null;
    donotbulkpostalmail?: boolean | null;
    donotemail?: boolean | null;
    donotfax?: boolean | null;
    donotphone?: boolean | null;
    donotpostalmail?: boolean | null;
    donotsendmm?: boolean | null;
    educationcode?: contact_educationcode | null;
    emailaddress1?: string | null;
    emailaddress2?: string | null;
    emailaddress3?: string | null;
    employeeid?: string | null;
    entityimageid?: string | null;
    exchangerate?: number | null;
    externaluseridentifier?: string | null;
    familystatuscode?: contact_familystatuscode | null;
    fax?: string | null;
    firstname?: string | null;
    followemail?: boolean | null;
    ftpsiteurl?: string | null;
    fullname?: string | null;
    gendercode?: contact_gendercode | null;
    governmentid?: string | null;
    haschildrencode?: contact_haschildrencode | null;
    home2?: string | null;
    importsequencenumber?: number | null;
    isautocreate?: boolean | null;
    isbackofficecustomer?: boolean | null;
    isprivate?: boolean | null;
    jobtitle?: string | null;
    lastname?: string | null;
    lastonholdtime?: Date | null;
    lastusedincampaign?: Date | null;
    leadsourcecode?: contact_leadsourcecode | null;
    managername?: string | null;
    managerphone?: string | null;
    marketingonly?: boolean | null;
    merged?: boolean | null;
    middlename?: string | null;
    mobilephone?: string | null;
    modifiedon?: Date | null;
    msdyn_disablewebtracking?: boolean | null;
    msdyn_isminor?: boolean | null;
    msdyn_isminorwithparentalconsent?: boolean | null;
    msdyn_portaltermsagreementdate?: Date | null;
    nickname?: string | null;
    numberofchildren?: number | null;
    onholdtime?: number | null;
    overriddencreatedon?: Date | null;
    pager?: string | null;
    participatesinworkflow?: boolean | null;
    paymenttermscode?: contact_paymenttermscode | null;
    preferredappointmentdaycode?: contact_preferredappointmentdaycode | null;
    preferredappointmenttimecode?: contact_preferredappointmenttimecode | null;
    preferredcontactmethodcode?: contact_preferredcontactmethodcode | null;
    processid?: string | null;
    salutation?: string | null;
    shippingmethodcode?: contact_shippingmethodcode | null;
    spousesname?: string | null;
    stageid?: string | null;
    statecode?: contact_statecode | null;
    statuscode?: contact_statuscode | null;
    subscriptionid?: string | null;
    suffix?: string | null;
    telephone1?: string | null;
    telephone2?: string | null;
    telephone3?: string | null;
    territorycode?: contact_territorycode | null;
    timespentbymeonemailandmeetings?: string | null;
    timezoneruleversionnumber?: number | null;
    transactioncurrencyid_guid?: string | null;
    traversedpath?: string | null;
    utcconversiontimezonecode?: number | null;
    versionnumber?: number | null;
    websiteurl?: string | null;
  }
  interface Contact_Relationships {
    account_primary_contact?: Account_Result[] | null;
    contact_activity_parties?: ActivityParty_Result[] | null;
    contact_connections1?: Connection_Result[] | null;
    contact_connections2?: Connection_Result[] | null;
    contact_customer_contacts?: Contact_Result[] | null;
    contact_master_contact?: Contact_Result[] | null;
    parentcustomerid_account?: Account_Result | null;
    parentcustomerid_contact?: Contact_Result | null;
  }
  interface Contact extends Contact_Base, Contact_Relationships {
    adx_preferredlanguageid_bind$adx_portallanguages?: string | null;
    msa_managingpartnerid_bind$accounts?: string | null;
    ownerid_bind$systemusers?: string | null;
    ownerid_bind$teams?: string | null;
    parentcustomerid_account_bind$accounts?: string | null;
    parentcustomerid_contact_bind$contacts?: string | null;
    preferredsystemuserid_bind$systemusers?: string | null;
    sla_contact_sla_bind$slas?: string | null;
    stageid_processstage_bind$processstages?: string | null;
    transactioncurrencyid_bind$transactioncurrencies?: string | null;
  }
  interface Contact_Create extends Contact {
  }
  interface Contact_Update extends Contact {
  }
  interface Contact_Select {
    accountid_guid: WebAttribute<Contact_Select, { accountid_guid: string | null }, { accountid_formatted?: string }>;
    accountrolecode: WebAttribute<Contact_Select, { accountrolecode: contact_accountrolecode | null }, { accountrolecode_formatted?: string }>;
    address1_addressid: WebAttribute<Contact_Select, { address1_addressid: string | null }, {  }>;
    address1_addresstypecode: WebAttribute<Contact_Select, { address1_addresstypecode: contact_address1_addresstypecode | null }, { address1_addresstypecode_formatted?: string }>;
    address1_city: WebAttribute<Contact_Select, { address1_city: string | null }, {  }>;
    address1_composite: WebAttribute<Contact_Select, { address1_composite: string | null }, {  }>;
    address1_country: WebAttribute<Contact_Select, { address1_country: string | null }, {  }>;
    address1_county: WebAttribute<Contact_Select, { address1_county: string | null }, {  }>;
    address1_fax: WebAttribute<Contact_Select, { address1_fax: string | null }, {  }>;
    address1_freighttermscode: WebAttribute<Contact_Select, { address1_freighttermscode: contact_address1_freighttermscode | null }, { address1_freighttermscode_formatted?: string }>;
    address1_latitude: WebAttribute<Contact_Select, { address1_latitude: number | null }, {  }>;
    address1_line1: WebAttribute<Contact_Select, { address1_line1: string | null }, {  }>;
    address1_line2: WebAttribute<Contact_Select, { address1_line2: string | null }, {  }>;
    address1_line3: WebAttribute<Contact_Select, { address1_line3: string | null }, {  }>;
    address1_longitude: WebAttribute<Contact_Select, { address1_longitude: number | null }, {  }>;
    address1_name: WebAttribute<Contact_Select, { address1_name: string | null }, {  }>;
    address1_postalcode: WebAttribute<Contact_Select, { address1_postalcode: string | null }, {  }>;
    address1_postofficebox: WebAttribute<Contact_Select, { address1_postofficebox: string | null }, {  }>;
    address1_primarycontactname: WebAttribute<Contact_Select, { address1_primarycontactname: string | null }, {  }>;
    address1_shippingmethodcode: WebAttribute<Contact_Select, { address1_shippingmethodcode: contact_address1_shippingmethodcode | null }, { address1_shippingmethodcode_formatted?: string }>;
    address1_stateorprovince: WebAttribute<Contact_Select, { address1_stateorprovince: string | null }, {  }>;
    address1_telephone1: WebAttribute<Contact_Select, { address1_telephone1: string | null }, {  }>;
    address1_telephone2: WebAttribute<Contact_Select, { address1_telephone2: string | null }, {  }>;
    address1_telephone3: WebAttribute<Contact_Select, { address1_telephone3: string | null }, {  }>;
    address1_upszone: WebAttribute<Contact_Select, { address1_upszone: string | null }, {  }>;
    address1_utcoffset: WebAttribute<Contact_Select, { address1_utcoffset: number | null }, {  }>;
    address2_addressid: WebAttribute<Contact_Select, { address2_addressid: string | null }, {  }>;
    address2_addresstypecode: WebAttribute<Contact_Select, { address2_addresstypecode: contact_address2_addresstypecode | null }, { address2_addresstypecode_formatted?: string }>;
    address2_city: WebAttribute<Contact_Select, { address2_city: string | null }, {  }>;
    address2_composite: WebAttribute<Contact_Select, { address2_composite: string | null }, {  }>;
    address2_country: WebAttribute<Contact_Select, { address2_country: string | null }, {  }>;
    address2_county: WebAttribute<Contact_Select, { address2_county: string | null }, {  }>;
    address2_fax: WebAttribute<Contact_Select, { address2_fax: string | null }, {  }>;
    address2_freighttermscode: WebAttribute<Contact_Select, { address2_freighttermscode: contact_address2_freighttermscode | null }, { address2_freighttermscode_formatted?: string }>;
    address2_latitude: WebAttribute<Contact_Select, { address2_latitude: number | null }, {  }>;
    address2_line1: WebAttribute<Contact_Select, { address2_line1: string | null }, {  }>;
    address2_line2: WebAttribute<Contact_Select, { address2_line2: string | null }, {  }>;
    address2_line3: WebAttribute<Contact_Select, { address2_line3: string | null }, {  }>;
    address2_longitude: WebAttribute<Contact_Select, { address2_longitude: number | null }, {  }>;
    address2_name: WebAttribute<Contact_Select, { address2_name: string | null }, {  }>;
    address2_postalcode: WebAttribute<Contact_Select, { address2_postalcode: string | null }, {  }>;
    address2_postofficebox: WebAttribute<Contact_Select, { address2_postofficebox: string | null }, {  }>;
    address2_primarycontactname: WebAttribute<Contact_Select, { address2_primarycontactname: string | null }, {  }>;
    address2_shippingmethodcode: WebAttribute<Contact_Select, { address2_shippingmethodcode: contact_address2_shippingmethodcode | null }, { address2_shippingmethodcode_formatted?: string }>;
    address2_stateorprovince: WebAttribute<Contact_Select, { address2_stateorprovince: string | null }, {  }>;
    address2_telephone1: WebAttribute<Contact_Select, { address2_telephone1: string | null }, {  }>;
    address2_telephone2: WebAttribute<Contact_Select, { address2_telephone2: string | null }, {  }>;
    address2_telephone3: WebAttribute<Contact_Select, { address2_telephone3: string | null }, {  }>;
    address2_upszone: WebAttribute<Contact_Select, { address2_upszone: string | null }, {  }>;
    address2_utcoffset: WebAttribute<Contact_Select, { address2_utcoffset: number | null }, {  }>;
    address3_addressid: WebAttribute<Contact_Select, { address3_addressid: string | null }, {  }>;
    address3_addresstypecode: WebAttribute<Contact_Select, { address3_addresstypecode: contact_address3_addresstypecode | null }, { address3_addresstypecode_formatted?: string }>;
    address3_city: WebAttribute<Contact_Select, { address3_city: string | null }, {  }>;
    address3_composite: WebAttribute<Contact_Select, { address3_composite: string | null }, {  }>;
    address3_country: WebAttribute<Contact_Select, { address3_country: string | null }, {  }>;
    address3_county: WebAttribute<Contact_Select, { address3_county: string | null }, {  }>;
    address3_fax: WebAttribute<Contact_Select, { address3_fax: string | null }, {  }>;
    address3_freighttermscode: WebAttribute<Contact_Select, { address3_freighttermscode: contact_address3_freighttermscode | null }, { address3_freighttermscode_formatted?: string }>;
    address3_latitude: WebAttribute<Contact_Select, { address3_latitude: number | null }, {  }>;
    address3_line1: WebAttribute<Contact_Select, { address3_line1: string | null }, {  }>;
    address3_line2: WebAttribute<Contact_Select, { address3_line2: string | null }, {  }>;
    address3_line3: WebAttribute<Contact_Select, { address3_line3: string | null }, {  }>;
    address3_longitude: WebAttribute<Contact_Select, { address3_longitude: number | null }, {  }>;
    address3_name: WebAttribute<Contact_Select, { address3_name: string | null }, {  }>;
    address3_postalcode: WebAttribute<Contact_Select, { address3_postalcode: string | null }, {  }>;
    address3_postofficebox: WebAttribute<Contact_Select, { address3_postofficebox: string | null }, {  }>;
    address3_primarycontactname: WebAttribute<Contact_Select, { address3_primarycontactname: string | null }, {  }>;
    address3_shippingmethodcode: WebAttribute<Contact_Select, { address3_shippingmethodcode: contact_address3_shippingmethodcode | null }, { address3_shippingmethodcode_formatted?: string }>;
    address3_stateorprovince: WebAttribute<Contact_Select, { address3_stateorprovince: string | null }, {  }>;
    address3_telephone1: WebAttribute<Contact_Select, { address3_telephone1: string | null }, {  }>;
    address3_telephone2: WebAttribute<Contact_Select, { address3_telephone2: string | null }, {  }>;
    address3_telephone3: WebAttribute<Contact_Select, { address3_telephone3: string | null }, {  }>;
    address3_upszone: WebAttribute<Contact_Select, { address3_upszone: string | null }, {  }>;
    address3_utcoffset: WebAttribute<Contact_Select, { address3_utcoffset: number | null }, {  }>;
    adx_confirmremovepassword: WebAttribute<Contact_Select, { adx_confirmremovepassword: boolean | null }, {  }>;
    adx_createdbyipaddress: WebAttribute<Contact_Select, { adx_createdbyipaddress: string | null }, {  }>;
    adx_createdbyusername: WebAttribute<Contact_Select, { adx_createdbyusername: string | null }, {  }>;
    adx_identity_accessfailedcount: WebAttribute<Contact_Select, { adx_identity_accessfailedcount: number | null }, {  }>;
    adx_identity_emailaddress1confirmed: WebAttribute<Contact_Select, { adx_identity_emailaddress1confirmed: boolean | null }, {  }>;
    adx_identity_lastsuccessfullogin: WebAttribute<Contact_Select, { adx_identity_lastsuccessfullogin: Date | null }, { adx_identity_lastsuccessfullogin_formatted?: string }>;
    adx_identity_locallogindisabled: WebAttribute<Contact_Select, { adx_identity_locallogindisabled: boolean | null }, {  }>;
    adx_identity_lockoutenabled: WebAttribute<Contact_Select, { adx_identity_lockoutenabled: boolean | null }, {  }>;
    adx_identity_lockoutenddate: WebAttribute<Contact_Select, { adx_identity_lockoutenddate: Date | null }, { adx_identity_lockoutenddate_formatted?: string }>;
    adx_identity_logonenabled: WebAttribute<Contact_Select, { adx_identity_logonenabled: boolean | null }, {  }>;
    adx_identity_mobilephoneconfirmed: WebAttribute<Contact_Select, { adx_identity_mobilephoneconfirmed: boolean | null }, {  }>;
    adx_identity_newpassword: WebAttribute<Contact_Select, { adx_identity_newpassword: string | null }, {  }>;
    adx_identity_passwordhash: WebAttribute<Contact_Select, { adx_identity_passwordhash: string | null }, {  }>;
    adx_identity_securitystamp: WebAttribute<Contact_Select, { adx_identity_securitystamp: string | null }, {  }>;
    adx_identity_twofactorenabled: WebAttribute<Contact_Select, { adx_identity_twofactorenabled: boolean | null }, {  }>;
    adx_identity_username: WebAttribute<Contact_Select, { adx_identity_username: string | null }, {  }>;
    adx_modifiedbyipaddress: WebAttribute<Contact_Select, { adx_modifiedbyipaddress: string | null }, {  }>;
    adx_modifiedbyusername: WebAttribute<Contact_Select, { adx_modifiedbyusername: string | null }, {  }>;
    adx_organizationname: WebAttribute<Contact_Select, { adx_organizationname: string | null }, {  }>;
    adx_preferredlanguageid_guid: WebAttribute<Contact_Select, { adx_preferredlanguageid_guid: string | null }, { adx_preferredlanguageid_formatted?: string }>;
    adx_profilealert: WebAttribute<Contact_Select, { adx_profilealert: boolean | null }, {  }>;
    adx_profilealertdate: WebAttribute<Contact_Select, { adx_profilealertdate: Date | null }, { adx_profilealertdate_formatted?: string }>;
    adx_profilealertinstructions: WebAttribute<Contact_Select, { adx_profilealertinstructions: string | null }, {  }>;
    adx_profileisanonymous: WebAttribute<Contact_Select, { adx_profileisanonymous: boolean | null }, {  }>;
    adx_profilelastactivity: WebAttribute<Contact_Select, { adx_profilelastactivity: Date | null }, { adx_profilelastactivity_formatted?: string }>;
    adx_profilemodifiedon: WebAttribute<Contact_Select, { adx_profilemodifiedon: Date | null }, { adx_profilemodifiedon_formatted?: string }>;
    adx_publicprofilecopy: WebAttribute<Contact_Select, { adx_publicprofilecopy: string | null }, {  }>;
    adx_timezone: WebAttribute<Contact_Select, { adx_timezone: number | null }, {  }>;
    aging30: WebAttribute<Contact_Select, { aging30: number | null; transactioncurrencyid_guid: string | null }, { aging30_formatted?: string; transactioncurrencyid_formatted?: string }>;
    aging30_base: WebAttribute<Contact_Select, { aging30_base: number | null; transactioncurrencyid_guid: string | null }, { aging30_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    aging60: WebAttribute<Contact_Select, { aging60: number | null; transactioncurrencyid_guid: string | null }, { aging60_formatted?: string; transactioncurrencyid_formatted?: string }>;
    aging60_base: WebAttribute<Contact_Select, { aging60_base: number | null; transactioncurrencyid_guid: string | null }, { aging60_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    aging90: WebAttribute<Contact_Select, { aging90: number | null; transactioncurrencyid_guid: string | null }, { aging90_formatted?: string; transactioncurrencyid_formatted?: string }>;
    aging90_base: WebAttribute<Contact_Select, { aging90_base: number | null; transactioncurrencyid_guid: string | null }, { aging90_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    anniversary: WebAttribute<Contact_Select, { anniversary: Date | null }, { anniversary_formatted?: string }>;
    annualincome: WebAttribute<Contact_Select, { annualincome: number | null; transactioncurrencyid_guid: string | null }, { annualincome_formatted?: string; transactioncurrencyid_formatted?: string }>;
    annualincome_base: WebAttribute<Contact_Select, { annualincome_base: number | null; transactioncurrencyid_guid: string | null }, { annualincome_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    assistantname: WebAttribute<Contact_Select, { assistantname: string | null }, {  }>;
    assistantphone: WebAttribute<Contact_Select, { assistantphone: string | null }, {  }>;
    birthdate: WebAttribute<Contact_Select, { birthdate: Date | null }, { birthdate_formatted?: string }>;
    business2: WebAttribute<Contact_Select, { business2: string | null }, {  }>;
    callback: WebAttribute<Contact_Select, { callback: string | null }, {  }>;
    childrensnames: WebAttribute<Contact_Select, { childrensnames: string | null }, {  }>;
    company: WebAttribute<Contact_Select, { company: string | null }, {  }>;
    contactid: WebAttribute<Contact_Select, { contactid: string | null }, {  }>;
    createdby_guid: WebAttribute<Contact_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdbyexternalparty_guid: WebAttribute<Contact_Select, { createdbyexternalparty_guid: string | null }, { createdbyexternalparty_formatted?: string }>;
    createdon: WebAttribute<Contact_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<Contact_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    creditlimit: WebAttribute<Contact_Select, { creditlimit: number | null; transactioncurrencyid_guid: string | null }, { creditlimit_formatted?: string; transactioncurrencyid_formatted?: string }>;
    creditlimit_base: WebAttribute<Contact_Select, { creditlimit_base: number | null; transactioncurrencyid_guid: string | null }, { creditlimit_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
    creditonhold: WebAttribute<Contact_Select, { creditonhold: boolean | null }, {  }>;
    customersizecode: WebAttribute<Contact_Select, { customersizecode: contact_customersizecode | null }, { customersizecode_formatted?: string }>;
    customertypecode: WebAttribute<Contact_Select, { customertypecode: contact_customertypecode | null }, { customertypecode_formatted?: string }>;
    department: WebAttribute<Contact_Select, { department: string | null }, {  }>;
    description: WebAttribute<Contact_Select, { description: string | null }, {  }>;
    donotbulkemail: WebAttribute<Contact_Select, { donotbulkemail: boolean | null }, {  }>;
    donotbulkpostalmail: WebAttribute<Contact_Select, { donotbulkpostalmail: boolean | null }, {  }>;
    donotemail: WebAttribute<Contact_Select, { donotemail: boolean | null }, {  }>;
    donotfax: WebAttribute<Contact_Select, { donotfax: boolean | null }, {  }>;
    donotphone: WebAttribute<Contact_Select, { donotphone: boolean | null }, {  }>;
    donotpostalmail: WebAttribute<Contact_Select, { donotpostalmail: boolean | null }, {  }>;
    donotsendmm: WebAttribute<Contact_Select, { donotsendmm: boolean | null }, {  }>;
    educationcode: WebAttribute<Contact_Select, { educationcode: contact_educationcode | null }, { educationcode_formatted?: string }>;
    emailaddress1: WebAttribute<Contact_Select, { emailaddress1: string | null }, {  }>;
    emailaddress2: WebAttribute<Contact_Select, { emailaddress2: string | null }, {  }>;
    emailaddress3: WebAttribute<Contact_Select, { emailaddress3: string | null }, {  }>;
    employeeid: WebAttribute<Contact_Select, { employeeid: string | null }, {  }>;
    entityimageid: WebAttribute<Contact_Select, { entityimageid: string | null }, {  }>;
    exchangerate: WebAttribute<Contact_Select, { exchangerate: number | null }, {  }>;
    externaluseridentifier: WebAttribute<Contact_Select, { externaluseridentifier: string | null }, {  }>;
    familystatuscode: WebAttribute<Contact_Select, { familystatuscode: contact_familystatuscode | null }, { familystatuscode_formatted?: string }>;
    fax: WebAttribute<Contact_Select, { fax: string | null }, {  }>;
    firstname: WebAttribute<Contact_Select, { firstname: string | null }, {  }>;
    followemail: WebAttribute<Contact_Select, { followemail: boolean | null }, {  }>;
    ftpsiteurl: WebAttribute<Contact_Select, { ftpsiteurl: string | null }, {  }>;
    fullname: WebAttribute<Contact_Select, { fullname: string | null }, {  }>;
    gendercode: WebAttribute<Contact_Select, { gendercode: contact_gendercode | null }, { gendercode_formatted?: string }>;
    governmentid: WebAttribute<Contact_Select, { governmentid: string | null }, {  }>;
    haschildrencode: WebAttribute<Contact_Select, { haschildrencode: contact_haschildrencode | null }, { haschildrencode_formatted?: string }>;
    home2: WebAttribute<Contact_Select, { home2: string | null }, {  }>;
    importsequencenumber: WebAttribute<Contact_Select, { importsequencenumber: number | null }, {  }>;
    isautocreate: WebAttribute<Contact_Select, { isautocreate: boolean | null }, {  }>;
    isbackofficecustomer: WebAttribute<Contact_Select, { isbackofficecustomer: boolean | null }, {  }>;
    isprivate: WebAttribute<Contact_Select, { isprivate: boolean | null }, {  }>;
    jobtitle: WebAttribute<Contact_Select, { jobtitle: string | null }, {  }>;
    lastname: WebAttribute<Contact_Select, { lastname: string | null }, {  }>;
    lastonholdtime: WebAttribute<Contact_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
    lastusedincampaign: WebAttribute<Contact_Select, { lastusedincampaign: Date | null }, { lastusedincampaign_formatted?: string }>;
    leadsourcecode: WebAttribute<Contact_Select, { leadsourcecode: contact_leadsourcecode | null }, { leadsourcecode_formatted?: string }>;
    managername: WebAttribute<Contact_Select, { managername: string | null }, {  }>;
    managerphone: WebAttribute<Contact_Select, { managerphone: string | null }, {  }>;
    marketingonly: WebAttribute<Contact_Select, { marketingonly: boolean | null }, {  }>;
    masterid_guid: WebAttribute<Contact_Select, { masterid_guid: string | null }, { masterid_formatted?: string }>;
    merged: WebAttribute<Contact_Select, { merged: boolean | null }, {  }>;
    middlename: WebAttribute<Contact_Select, { middlename: string | null }, {  }>;
    mobilephone: WebAttribute<Contact_Select, { mobilephone: string | null }, {  }>;
    modifiedby_guid: WebAttribute<Contact_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedbyexternalparty_guid: WebAttribute<Contact_Select, { modifiedbyexternalparty_guid: string | null }, { modifiedbyexternalparty_formatted?: string }>;
    modifiedon: WebAttribute<Contact_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<Contact_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    msa_managingpartnerid_guid: WebAttribute<Contact_Select, { msa_managingpartnerid_guid: string | null }, { msa_managingpartnerid_formatted?: string }>;
    msdyn_disablewebtracking: WebAttribute<Contact_Select, { msdyn_disablewebtracking: boolean | null }, {  }>;
    msdyn_isminor: WebAttribute<Contact_Select, { msdyn_isminor: boolean | null }, {  }>;
    msdyn_isminorwithparentalconsent: WebAttribute<Contact_Select, { msdyn_isminorwithparentalconsent: boolean | null }, {  }>;
    msdyn_portaltermsagreementdate: WebAttribute<Contact_Select, { msdyn_portaltermsagreementdate: Date | null }, { msdyn_portaltermsagreementdate_formatted?: string }>;
    nickname: WebAttribute<Contact_Select, { nickname: string | null }, {  }>;
    numberofchildren: WebAttribute<Contact_Select, { numberofchildren: number | null }, {  }>;
    onholdtime: WebAttribute<Contact_Select, { onholdtime: number | null }, {  }>;
    overriddencreatedon: WebAttribute<Contact_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
    ownerid_guid: WebAttribute<Contact_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<Contact_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<Contact_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<Contact_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    pager: WebAttribute<Contact_Select, { pager: string | null }, {  }>;
    parentcontactid_guid: WebAttribute<Contact_Select, { parentcontactid_guid: string | null }, { parentcontactid_formatted?: string }>;
    parentcustomerid_guid: WebAttribute<Contact_Select, { parentcustomerid_guid: string | null }, { parentcustomerid_formatted?: string }>;
    participatesinworkflow: WebAttribute<Contact_Select, { participatesinworkflow: boolean | null }, {  }>;
    paymenttermscode: WebAttribute<Contact_Select, { paymenttermscode: contact_paymenttermscode | null }, { paymenttermscode_formatted?: string }>;
    preferredappointmentdaycode: WebAttribute<Contact_Select, { preferredappointmentdaycode: contact_preferredappointmentdaycode | null }, { preferredappointmentdaycode_formatted?: string }>;
    preferredappointmenttimecode: WebAttribute<Contact_Select, { preferredappointmenttimecode: contact_preferredappointmenttimecode | null }, { preferredappointmenttimecode_formatted?: string }>;
    preferredcontactmethodcode: WebAttribute<Contact_Select, { preferredcontactmethodcode: contact_preferredcontactmethodcode | null }, { preferredcontactmethodcode_formatted?: string }>;
    preferredsystemuserid_guid: WebAttribute<Contact_Select, { preferredsystemuserid_guid: string | null }, { preferredsystemuserid_formatted?: string }>;
    processid: WebAttribute<Contact_Select, { processid: string | null }, {  }>;
    salutation: WebAttribute<Contact_Select, { salutation: string | null }, {  }>;
    shippingmethodcode: WebAttribute<Contact_Select, { shippingmethodcode: contact_shippingmethodcode | null }, { shippingmethodcode_formatted?: string }>;
    slaid_guid: WebAttribute<Contact_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
    slainvokedid_guid: WebAttribute<Contact_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
    spousesname: WebAttribute<Contact_Select, { spousesname: string | null }, {  }>;
    stageid: WebAttribute<Contact_Select, { stageid: string | null }, {  }>;
    statecode: WebAttribute<Contact_Select, { statecode: contact_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<Contact_Select, { statuscode: contact_statuscode | null }, { statuscode_formatted?: string }>;
    subscriptionid: WebAttribute<Contact_Select, { subscriptionid: string | null }, {  }>;
    suffix: WebAttribute<Contact_Select, { suffix: string | null }, {  }>;
    telephone1: WebAttribute<Contact_Select, { telephone1: string | null }, {  }>;
    telephone2: WebAttribute<Contact_Select, { telephone2: string | null }, {  }>;
    telephone3: WebAttribute<Contact_Select, { telephone3: string | null }, {  }>;
    territorycode: WebAttribute<Contact_Select, { territorycode: contact_territorycode | null }, { territorycode_formatted?: string }>;
    timespentbymeonemailandmeetings: WebAttribute<Contact_Select, { timespentbymeonemailandmeetings: string | null }, {  }>;
    timezoneruleversionnumber: WebAttribute<Contact_Select, { timezoneruleversionnumber: number | null }, {  }>;
    transactioncurrencyid_guid: WebAttribute<Contact_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
    traversedpath: WebAttribute<Contact_Select, { traversedpath: string | null }, {  }>;
    utcconversiontimezonecode: WebAttribute<Contact_Select, { utcconversiontimezonecode: number | null }, {  }>;
    versionnumber: WebAttribute<Contact_Select, { versionnumber: number | null }, {  }>;
    websiteurl: WebAttribute<Contact_Select, { websiteurl: string | null }, {  }>;
  }
  interface Contact_Filter {
    accountid_guid: XQW.Guid;
    accountrolecode: contact_accountrolecode;
    address1_addressid: XQW.Guid;
    address1_addresstypecode: contact_address1_addresstypecode;
    address1_city: string;
    address1_composite: string;
    address1_country: string;
    address1_county: string;
    address1_fax: string;
    address1_freighttermscode: contact_address1_freighttermscode;
    address1_latitude: number;
    address1_line1: string;
    address1_line2: string;
    address1_line3: string;
    address1_longitude: number;
    address1_name: string;
    address1_postalcode: string;
    address1_postofficebox: string;
    address1_primarycontactname: string;
    address1_shippingmethodcode: contact_address1_shippingmethodcode;
    address1_stateorprovince: string;
    address1_telephone1: string;
    address1_telephone2: string;
    address1_telephone3: string;
    address1_upszone: string;
    address1_utcoffset: number;
    address2_addressid: XQW.Guid;
    address2_addresstypecode: contact_address2_addresstypecode;
    address2_city: string;
    address2_composite: string;
    address2_country: string;
    address2_county: string;
    address2_fax: string;
    address2_freighttermscode: contact_address2_freighttermscode;
    address2_latitude: number;
    address2_line1: string;
    address2_line2: string;
    address2_line3: string;
    address2_longitude: number;
    address2_name: string;
    address2_postalcode: string;
    address2_postofficebox: string;
    address2_primarycontactname: string;
    address2_shippingmethodcode: contact_address2_shippingmethodcode;
    address2_stateorprovince: string;
    address2_telephone1: string;
    address2_telephone2: string;
    address2_telephone3: string;
    address2_upszone: string;
    address2_utcoffset: number;
    address3_addressid: XQW.Guid;
    address3_addresstypecode: contact_address3_addresstypecode;
    address3_city: string;
    address3_composite: string;
    address3_country: string;
    address3_county: string;
    address3_fax: string;
    address3_freighttermscode: contact_address3_freighttermscode;
    address3_latitude: number;
    address3_line1: string;
    address3_line2: string;
    address3_line3: string;
    address3_longitude: number;
    address3_name: string;
    address3_postalcode: string;
    address3_postofficebox: string;
    address3_primarycontactname: string;
    address3_shippingmethodcode: contact_address3_shippingmethodcode;
    address3_stateorprovince: string;
    address3_telephone1: string;
    address3_telephone2: string;
    address3_telephone3: string;
    address3_upszone: string;
    address3_utcoffset: number;
    adx_confirmremovepassword: boolean;
    adx_createdbyipaddress: string;
    adx_createdbyusername: string;
    adx_identity_accessfailedcount: number;
    adx_identity_emailaddress1confirmed: boolean;
    adx_identity_lastsuccessfullogin: Date;
    adx_identity_locallogindisabled: boolean;
    adx_identity_lockoutenabled: boolean;
    adx_identity_lockoutenddate: Date;
    adx_identity_logonenabled: boolean;
    adx_identity_mobilephoneconfirmed: boolean;
    adx_identity_newpassword: string;
    adx_identity_passwordhash: string;
    adx_identity_securitystamp: string;
    adx_identity_twofactorenabled: boolean;
    adx_identity_username: string;
    adx_modifiedbyipaddress: string;
    adx_modifiedbyusername: string;
    adx_organizationname: string;
    adx_preferredlanguageid_guid: XQW.Guid;
    adx_profilealert: boolean;
    adx_profilealertdate: Date;
    adx_profilealertinstructions: string;
    adx_profileisanonymous: boolean;
    adx_profilelastactivity: Date;
    adx_profilemodifiedon: Date;
    adx_publicprofilecopy: string;
    adx_timezone: number;
    aging30: number;
    aging30_base: number;
    aging60: number;
    aging60_base: number;
    aging90: number;
    aging90_base: number;
    anniversary: Date;
    annualincome: number;
    annualincome_base: number;
    assistantname: string;
    assistantphone: string;
    birthdate: Date;
    business2: string;
    callback: string;
    childrensnames: string;
    company: string;
    contactid: XQW.Guid;
    createdby_guid: XQW.Guid;
    createdbyexternalparty_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    creditlimit: number;
    creditlimit_base: number;
    creditonhold: boolean;
    customersizecode: contact_customersizecode;
    customertypecode: contact_customertypecode;
    department: string;
    description: string;
    donotbulkemail: boolean;
    donotbulkpostalmail: boolean;
    donotemail: boolean;
    donotfax: boolean;
    donotphone: boolean;
    donotpostalmail: boolean;
    donotsendmm: boolean;
    educationcode: contact_educationcode;
    emailaddress1: string;
    emailaddress2: string;
    emailaddress3: string;
    employeeid: string;
    entityimageid: XQW.Guid;
    exchangerate: any;
    externaluseridentifier: string;
    familystatuscode: contact_familystatuscode;
    fax: string;
    firstname: string;
    followemail: boolean;
    ftpsiteurl: string;
    fullname: string;
    gendercode: contact_gendercode;
    governmentid: string;
    haschildrencode: contact_haschildrencode;
    home2: string;
    importsequencenumber: number;
    isautocreate: boolean;
    isbackofficecustomer: boolean;
    isprivate: boolean;
    jobtitle: string;
    lastname: string;
    lastonholdtime: Date;
    lastusedincampaign: Date;
    leadsourcecode: contact_leadsourcecode;
    managername: string;
    managerphone: string;
    marketingonly: boolean;
    masterid_guid: XQW.Guid;
    merged: boolean;
    middlename: string;
    mobilephone: string;
    modifiedby_guid: XQW.Guid;
    modifiedbyexternalparty_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    msa_managingpartnerid_guid: XQW.Guid;
    msdyn_disablewebtracking: boolean;
    msdyn_isminor: boolean;
    msdyn_isminorwithparentalconsent: boolean;
    msdyn_portaltermsagreementdate: Date;
    nickname: string;
    numberofchildren: number;
    onholdtime: number;
    overriddencreatedon: Date;
    ownerid_guid: XQW.Guid;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    pager: string;
    parentcontactid_guid: XQW.Guid;
    parentcustomerid_guid: XQW.Guid;
    participatesinworkflow: boolean;
    paymenttermscode: contact_paymenttermscode;
    preferredappointmentdaycode: contact_preferredappointmentdaycode;
    preferredappointmenttimecode: contact_preferredappointmenttimecode;
    preferredcontactmethodcode: contact_preferredcontactmethodcode;
    preferredsystemuserid_guid: XQW.Guid;
    processid: XQW.Guid;
    salutation: string;
    shippingmethodcode: contact_shippingmethodcode;
    slaid_guid: XQW.Guid;
    slainvokedid_guid: XQW.Guid;
    spousesname: string;
    stageid: XQW.Guid;
    statecode: contact_statecode;
    statuscode: contact_statuscode;
    subscriptionid: XQW.Guid;
    suffix: string;
    telephone1: string;
    telephone2: string;
    telephone3: string;
    territorycode: contact_territorycode;
    timespentbymeonemailandmeetings: string;
    timezoneruleversionnumber: number;
    transactioncurrencyid_guid: XQW.Guid;
    traversedpath: string;
    utcconversiontimezonecode: number;
    versionnumber: number;
    websiteurl: string;
  }
  interface Contact_Expand {
    account_primary_contact: WebExpand<Contact_Expand, Account_Select, Account_Filter, { account_primary_contact: Account_Result[] }>;
    contact_activity_parties: WebExpand<Contact_Expand, ActivityParty_Select, ActivityParty_Filter, { contact_activity_parties: ActivityParty_Result[] }>;
    contact_connections1: WebExpand<Contact_Expand, Connection_Select, Connection_Filter, { contact_connections1: Connection_Result[] }>;
    contact_connections2: WebExpand<Contact_Expand, Connection_Select, Connection_Filter, { contact_connections2: Connection_Result[] }>;
    contact_customer_contacts: WebExpand<Contact_Expand, Contact_Select, Contact_Filter, { contact_customer_contacts: Contact_Result[] }>;
    contact_master_contact: WebExpand<Contact_Expand, Contact_Select, Contact_Filter, { contact_master_contact: Contact_Result[] }>;
    masterid: WebExpand<Contact_Expand, Contact_Select, Contact_Filter, { masterid: Contact_Result }>;
    msa_managingpartnerid: WebExpand<Contact_Expand, Account_Select, Account_Filter, { msa_managingpartnerid: Account_Result }>;
    parentcustomerid_account: WebExpand<Contact_Expand, Account_Select, Account_Filter, { parentcustomerid_account: Account_Result }>;
    parentcustomerid_contact: WebExpand<Contact_Expand, Contact_Select, Contact_Filter, { parentcustomerid_contact: Contact_Result }>;
  }
  interface Contact_FormattedResult {
    accountid_formatted?: string;
    accountrolecode_formatted?: string;
    address1_addresstypecode_formatted?: string;
    address1_freighttermscode_formatted?: string;
    address1_shippingmethodcode_formatted?: string;
    address2_addresstypecode_formatted?: string;
    address2_freighttermscode_formatted?: string;
    address2_shippingmethodcode_formatted?: string;
    address3_addresstypecode_formatted?: string;
    address3_freighttermscode_formatted?: string;
    address3_shippingmethodcode_formatted?: string;
    adx_identity_lastsuccessfullogin_formatted?: string;
    adx_identity_lockoutenddate_formatted?: string;
    adx_preferredlanguageid_formatted?: string;
    adx_profilealertdate_formatted?: string;
    adx_profilelastactivity_formatted?: string;
    adx_profilemodifiedon_formatted?: string;
    aging30_base_formatted?: string;
    aging30_formatted?: string;
    aging60_base_formatted?: string;
    aging60_formatted?: string;
    aging90_base_formatted?: string;
    aging90_formatted?: string;
    anniversary_formatted?: string;
    annualincome_base_formatted?: string;
    annualincome_formatted?: string;
    birthdate_formatted?: string;
    createdby_formatted?: string;
    createdbyexternalparty_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    creditlimit_base_formatted?: string;
    creditlimit_formatted?: string;
    customersizecode_formatted?: string;
    customertypecode_formatted?: string;
    educationcode_formatted?: string;
    familystatuscode_formatted?: string;
    gendercode_formatted?: string;
    haschildrencode_formatted?: string;
    lastonholdtime_formatted?: string;
    lastusedincampaign_formatted?: string;
    leadsourcecode_formatted?: string;
    masterid_formatted?: string;
    modifiedby_formatted?: string;
    modifiedbyexternalparty_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    msa_managingpartnerid_formatted?: string;
    msdyn_portaltermsagreementdate_formatted?: string;
    overriddencreatedon_formatted?: string;
    ownerid_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    parentcontactid_formatted?: string;
    parentcustomerid_formatted?: string;
    paymenttermscode_formatted?: string;
    preferredappointmentdaycode_formatted?: string;
    preferredappointmenttimecode_formatted?: string;
    preferredcontactmethodcode_formatted?: string;
    preferredsystemuserid_formatted?: string;
    shippingmethodcode_formatted?: string;
    slaid_formatted?: string;
    slainvokedid_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
    territorycode_formatted?: string;
    transactioncurrencyid_formatted?: string;
  }
  interface Contact_Result extends Contact_Base, Contact_Relationships {
    "@odata.etag": string;
    accountid_guid: string | null;
    adx_preferredlanguageid_guid: string | null;
    createdby_guid: string | null;
    createdbyexternalparty_guid: string | null;
    createdonbehalfby_guid: string | null;
    masterid_guid: string | null;
    modifiedby_guid: string | null;
    modifiedbyexternalparty_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    msa_managingpartnerid_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
    parentcontactid_guid: string | null;
    parentcustomerid_guid: string | null;
    preferredsystemuserid_guid: string | null;
    slaid_guid: string | null;
    slainvokedid_guid: string | null;
    transactioncurrencyid_guid: string | null;
  }
  interface Contact_RelatedOne {
    masterid: WebMappingRetrieve<Web.Contact_Select,Web.Contact_Expand,Web.Contact_Filter,Web.Contact_Fixed,Web.Contact_Result,Web.Contact_FormattedResult>;
    msa_managingpartnerid: WebMappingRetrieve<Web.Account_Select,Web.Account_Expand,Web.Account_Filter,Web.Account_Fixed,Web.Account_Result,Web.Account_FormattedResult>;
    parentcustomerid_account: WebMappingRetrieve<Web.Account_Select,Web.Account_Expand,Web.Account_Filter,Web.Account_Fixed,Web.Account_Result,Web.Account_FormattedResult>;
    parentcustomerid_contact: WebMappingRetrieve<Web.Contact_Select,Web.Contact_Expand,Web.Contact_Filter,Web.Contact_Fixed,Web.Contact_Result,Web.Contact_FormattedResult>;
  }
  interface Contact_RelatedMany {
    account_primary_contact: WebMappingRetrieve<Web.Account_Select,Web.Account_Expand,Web.Account_Filter,Web.Account_Fixed,Web.Account_Result,Web.Account_FormattedResult>;
    contact_activity_parties: WebMappingRetrieve<Web.ActivityParty_Select,Web.ActivityParty_Expand,Web.ActivityParty_Filter,Web.ActivityParty_Fixed,Web.ActivityParty_Result,Web.ActivityParty_FormattedResult>;
    contact_connections1: WebMappingRetrieve<Web.Connection_Select,Web.Connection_Expand,Web.Connection_Filter,Web.Connection_Fixed,Web.Connection_Result,Web.Connection_FormattedResult>;
    contact_connections2: WebMappingRetrieve<Web.Connection_Select,Web.Connection_Expand,Web.Connection_Filter,Web.Connection_Fixed,Web.Connection_Result,Web.Connection_FormattedResult>;
    contact_customer_contacts: WebMappingRetrieve<Web.Contact_Select,Web.Contact_Expand,Web.Contact_Filter,Web.Contact_Fixed,Web.Contact_Result,Web.Contact_FormattedResult>;
    contact_master_contact: WebMappingRetrieve<Web.Contact_Select,Web.Contact_Expand,Web.Contact_Filter,Web.Contact_Fixed,Web.Contact_Result,Web.Contact_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  contacts: WebMappingRetrieve<Web.Contact_Select,Web.Contact_Expand,Web.Contact_Filter,Web.Contact_Fixed,Web.Contact_Result,Web.Contact_FormattedResult>;
}
interface WebEntitiesRelated {
  contacts: WebMappingRelated<Web.Contact_RelatedOne,Web.Contact_RelatedMany>;
}
interface WebEntitiesCUDA {
  contacts: WebMappingCUDA<Web.Contact_Create,Web.Contact_Update,Web.Contact_Select>;
}
