declare namespace Web {
  interface Email_Base extends WebEntity {
    activityadditionalparams?: string | null;
    activityid?: string | null;
    activitytypecode?: string | null;
    actualdurationminutes?: number | null;
    actualend?: Date | null;
    actualstart?: Date | null;
    attachmentcount?: number | null;
    attachmentopencount?: number | null;
    baseconversationindexhash?: number | null;
    category?: string | null;
    compressed?: boolean | null;
    conversationindex?: string | null;
    conversationtrackingid?: string | null;
    correlationmethod?: email_correlationmethod | null;
    createdon?: Date | null;
    delayedemailsendtime?: Date | null;
    deliveryattempts?: number | null;
    deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
    deliveryreceiptrequested?: boolean | null;
    description?: string | null;
    directioncode?: boolean | null;
    emailreminderexpirytime?: Date | null;
    emailreminderstatus?: email_reminderstatus | null;
    emailremindertext?: string | null;
    emailremindertype?: email_remindertype | null;
    emailtrackingid?: string | null;
    exchangerate?: number | null;
    followemailuserpreference?: boolean | null;
    importsequencenumber?: number | null;
    inreplyto?: string | null;
    isbilled?: boolean | null;
    isemailfollowed?: boolean | null;
    isemailreminderset?: boolean | null;
    isregularactivity?: boolean | null;
    isunsafe?: number | null;
    isworkflowcreated?: boolean | null;
    lastonholdtime?: Date | null;
    lastopenedtime?: Date | null;
    linksclickedcount?: number | null;
    messageid?: string | null;
    messageiddupcheck?: string | null;
    mimetype?: string | null;
    modifiedon?: Date | null;
    notifications?: email_notifications | null;
    onholdtime?: number | null;
    opencount?: number | null;
    overriddencreatedon?: Date | null;
    postponeemailprocessinguntil?: Date | null;
    prioritycode?: email_prioritycode | null;
    processid?: string | null;
    readreceiptrequested?: boolean | null;
    reminderactioncardid?: string | null;
    replycount?: number | null;
    scheduleddurationminutes?: number | null;
    scheduledend?: Date | null;
    scheduledstart?: Date | null;
    sender?: string | null;
    senton?: Date | null;
    sortdate?: Date | null;
    stageid?: string | null;
    statecode?: email_statecode | null;
    statuscode?: email_statuscode | null;
    subcategory?: string | null;
    subject?: string | null;
    submittedby?: string | null;
    timezoneruleversionnumber?: number | null;
    torecipients?: string | null;
    trackingtoken?: string | null;
    traversedpath?: string | null;
    utcconversiontimezonecode?: number | null;
    versionnumber?: number | null;
  }
  interface Email_Relationships {
    activityid_activitypointer?: ActivityPointer_Result | null;
    createdby_email?: SystemUser_Result | null;
    createdonbehalfby_email?: SystemUser_Result | null;
    email_activity_parties?: ActivityParty_Result[] | null;
    email_connections1?: Connection_Result[] | null;
    email_connections2?: Connection_Result[] | null;
    email_email_parentactivityid?: Email_Result[] | null;
    emailsender_account?: Account_Result | null;
    emailsender_contact?: Contact_Result | null;
    emailsender_systemuser?: SystemUser_Result | null;
    modifiedby_email?: SystemUser_Result | null;
    modifiedonbehalfby_email?: SystemUser_Result | null;
    owninguser_email?: SystemUser_Result | null;
    regardingobjectid_account_email?: Account_Result | null;
    regardingobjectid_contact_email?: Contact_Result | null;
  }
  interface Email extends Email_Base, Email_Relationships {
    regardingobjectid_account_email_bind$accounts?: string | null;
    regardingobjectid_adx_ad_email_bind$adx_ads?: string | null;
    regardingobjectid_adx_adplacement_email_bind$adx_adplacements?: string | null;
    regardingobjectid_adx_invitation_email_bind$adx_invitations?: string | null;
    regardingobjectid_adx_poll_email_bind$adx_polls?: string | null;
    regardingobjectid_adx_polloption_email_bind$adx_polloptions?: string | null;
    regardingobjectid_adx_pollplacement_email_bind$adx_pollplacements?: string | null;
    regardingobjectid_adx_pollsubmission_email_bind$adx_pollsubmissions?: string | null;
    regardingobjectid_adx_publishingstatetransitionrule_email_bind$adx_publishingstatetransitionrules?: string | null;
    regardingobjectid_adx_redirect_email_bind$adx_redirects?: string | null;
    regardingobjectid_adx_shortcut_email_bind$adx_shortcuts?: string | null;
    regardingobjectid_adx_webpage_email_bind$adx_webpages?: string | null;
    regardingobjectid_adx_website_email_bind$adx_websites?: string | null;
    regardingobjectid_asyncoperation_bind$asyncoperations?: string | null;
    regardingobjectid_contact_email_bind$contacts?: string | null;
    regardingobjectid_knowledgearticle_email_bind$knowledgearticles?: string | null;
    regardingobjectid_knowledgebaserecord_email_bind$knowledgebaserecords?: string | null;
    sla_email_sla_bind$slas?: string | null;
    stageid_processstage_bind$processstages?: string | null;
    templateid_bind$templates?: string | null;
    transactioncurrencyid_email_bind$transactioncurrencies?: string | null;
  }
  interface Email_Create extends Email {
    activityid_activitypointer_bind$activitypointers?: string | null;
    parentactivityid_bind$emails?: string | null;
  }
  interface Email_Update extends Email {
  }
  interface Email_Select {
    activityadditionalparams: WebAttribute<Email_Select, { activityadditionalparams: string | null }, {  }>;
    activityid: WebAttribute<Email_Select, { activityid: string | null }, {  }>;
    activitytypecode: WebAttribute<Email_Select, { activitytypecode: string | null }, {  }>;
    actualdurationminutes: WebAttribute<Email_Select, { actualdurationminutes: number | null }, {  }>;
    actualend: WebAttribute<Email_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
    actualstart: WebAttribute<Email_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
    attachmentcount: WebAttribute<Email_Select, { attachmentcount: number | null }, {  }>;
    attachmentopencount: WebAttribute<Email_Select, { attachmentopencount: number | null }, {  }>;
    baseconversationindexhash: WebAttribute<Email_Select, { baseconversationindexhash: number | null }, {  }>;
    bcc_guid: WebAttribute<Email_Select, { bcc_guid: string | null }, { bcc_formatted?: string }>;
    category: WebAttribute<Email_Select, { category: string | null }, {  }>;
    cc_guid: WebAttribute<Email_Select, { cc_guid: string | null }, { cc_formatted?: string }>;
    compressed: WebAttribute<Email_Select, { compressed: boolean | null }, {  }>;
    conversationindex: WebAttribute<Email_Select, { conversationindex: string | null }, {  }>;
    conversationtrackingid: WebAttribute<Email_Select, { conversationtrackingid: string | null }, {  }>;
    correlationmethod: WebAttribute<Email_Select, { correlationmethod: email_correlationmethod | null }, { correlationmethod_formatted?: string }>;
    createdby_guid: WebAttribute<Email_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdon: WebAttribute<Email_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<Email_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    delayedemailsendtime: WebAttribute<Email_Select, { delayedemailsendtime: Date | null }, { delayedemailsendtime_formatted?: string }>;
    deliveryattempts: WebAttribute<Email_Select, { deliveryattempts: number | null }, {  }>;
    deliveryprioritycode: WebAttribute<Email_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
    deliveryreceiptrequested: WebAttribute<Email_Select, { deliveryreceiptrequested: boolean | null }, {  }>;
    description: WebAttribute<Email_Select, { description: string | null }, {  }>;
    directioncode: WebAttribute<Email_Select, { directioncode: boolean | null }, {  }>;
    emailreminderexpirytime: WebAttribute<Email_Select, { emailreminderexpirytime: Date | null }, { emailreminderexpirytime_formatted?: string }>;
    emailreminderstatus: WebAttribute<Email_Select, { emailreminderstatus: email_reminderstatus | null }, { emailreminderstatus_formatted?: string }>;
    emailremindertext: WebAttribute<Email_Select, { emailremindertext: string | null }, {  }>;
    emailremindertype: WebAttribute<Email_Select, { emailremindertype: email_remindertype | null }, { emailremindertype_formatted?: string }>;
    emailsender_guid: WebAttribute<Email_Select, { emailsender_guid: string | null }, { emailsender_formatted?: string }>;
    emailtrackingid: WebAttribute<Email_Select, { emailtrackingid: string | null }, {  }>;
    exchangerate: WebAttribute<Email_Select, { exchangerate: number | null }, {  }>;
    followemailuserpreference: WebAttribute<Email_Select, { followemailuserpreference: boolean | null }, {  }>;
    from_guid: WebAttribute<Email_Select, { from_guid: string | null }, { from_formatted?: string }>;
    importsequencenumber: WebAttribute<Email_Select, { importsequencenumber: number | null }, {  }>;
    inreplyto: WebAttribute<Email_Select, { inreplyto: string | null }, {  }>;
    isbilled: WebAttribute<Email_Select, { isbilled: boolean | null }, {  }>;
    isemailfollowed: WebAttribute<Email_Select, { isemailfollowed: boolean | null }, {  }>;
    isemailreminderset: WebAttribute<Email_Select, { isemailreminderset: boolean | null }, {  }>;
    isregularactivity: WebAttribute<Email_Select, { isregularactivity: boolean | null }, {  }>;
    isunsafe: WebAttribute<Email_Select, { isunsafe: number | null }, {  }>;
    isworkflowcreated: WebAttribute<Email_Select, { isworkflowcreated: boolean | null }, {  }>;
    lastonholdtime: WebAttribute<Email_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
    lastopenedtime: WebAttribute<Email_Select, { lastopenedtime: Date | null }, { lastopenedtime_formatted?: string }>;
    linksclickedcount: WebAttribute<Email_Select, { linksclickedcount: number | null }, {  }>;
    messageid: WebAttribute<Email_Select, { messageid: string | null }, {  }>;
    messageiddupcheck: WebAttribute<Email_Select, { messageiddupcheck: string | null }, {  }>;
    mimetype: WebAttribute<Email_Select, { mimetype: string | null }, {  }>;
    modifiedby_guid: WebAttribute<Email_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedon: WebAttribute<Email_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<Email_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    notifications: WebAttribute<Email_Select, { notifications: email_notifications | null }, { notifications_formatted?: string }>;
    onholdtime: WebAttribute<Email_Select, { onholdtime: number | null }, {  }>;
    opencount: WebAttribute<Email_Select, { opencount: number | null }, {  }>;
    overriddencreatedon: WebAttribute<Email_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
    ownerid_guid: WebAttribute<Email_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<Email_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<Email_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<Email_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    parentactivityid_guid: WebAttribute<Email_Select, { parentactivityid_guid: string | null }, { parentactivityid_formatted?: string }>;
    postponeemailprocessinguntil: WebAttribute<Email_Select, { postponeemailprocessinguntil: Date | null }, { postponeemailprocessinguntil_formatted?: string }>;
    prioritycode: WebAttribute<Email_Select, { prioritycode: email_prioritycode | null }, { prioritycode_formatted?: string }>;
    processid: WebAttribute<Email_Select, { processid: string | null }, {  }>;
    readreceiptrequested: WebAttribute<Email_Select, { readreceiptrequested: boolean | null }, {  }>;
    regardingobjectid_guid: WebAttribute<Email_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
    reminderactioncardid: WebAttribute<Email_Select, { reminderactioncardid: string | null }, {  }>;
    replycount: WebAttribute<Email_Select, { replycount: number | null }, {  }>;
    scheduleddurationminutes: WebAttribute<Email_Select, { scheduleddurationminutes: number | null }, {  }>;
    scheduledend: WebAttribute<Email_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
    scheduledstart: WebAttribute<Email_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
    sender: WebAttribute<Email_Select, { sender: string | null }, {  }>;
    sendermailboxid_guid: WebAttribute<Email_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
    sendersaccount_guid: WebAttribute<Email_Select, { sendersaccount_guid: string | null }, { sendersaccount_formatted?: string }>;
    senton: WebAttribute<Email_Select, { senton: Date | null }, { senton_formatted?: string }>;
    slaid_guid: WebAttribute<Email_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
    slainvokedid_guid: WebAttribute<Email_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
    sortdate: WebAttribute<Email_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
    stageid: WebAttribute<Email_Select, { stageid: string | null }, {  }>;
    statecode: WebAttribute<Email_Select, { statecode: email_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<Email_Select, { statuscode: email_statuscode | null }, { statuscode_formatted?: string }>;
    subcategory: WebAttribute<Email_Select, { subcategory: string | null }, {  }>;
    subject: WebAttribute<Email_Select, { subject: string | null }, {  }>;
    submittedby: WebAttribute<Email_Select, { submittedby: string | null }, {  }>;
    templateid_guid: WebAttribute<Email_Select, { templateid_guid: string | null }, { templateid_formatted?: string }>;
    timezoneruleversionnumber: WebAttribute<Email_Select, { timezoneruleversionnumber: number | null }, {  }>;
    to_guid: WebAttribute<Email_Select, { to_guid: string | null }, { to_formatted?: string }>;
    torecipients: WebAttribute<Email_Select, { torecipients: string | null }, {  }>;
    trackingtoken: WebAttribute<Email_Select, { trackingtoken: string | null }, {  }>;
    transactioncurrencyid_guid: WebAttribute<Email_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
    traversedpath: WebAttribute<Email_Select, { traversedpath: string | null }, {  }>;
    utcconversiontimezonecode: WebAttribute<Email_Select, { utcconversiontimezonecode: number | null }, {  }>;
    versionnumber: WebAttribute<Email_Select, { versionnumber: number | null }, {  }>;
  }
  interface Email_Filter {
    activityadditionalparams: string;
    activityid: XQW.Guid;
    activitytypecode: string;
    actualdurationminutes: number;
    actualend: Date;
    actualstart: Date;
    attachmentcount: number;
    attachmentopencount: number;
    baseconversationindexhash: number;
    bcc_guid: XQW.Guid;
    category: string;
    cc_guid: XQW.Guid;
    compressed: boolean;
    conversationindex: string;
    conversationtrackingid: XQW.Guid;
    correlationmethod: email_correlationmethod;
    createdby_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    delayedemailsendtime: Date;
    deliveryattempts: number;
    deliveryprioritycode: activitypointer_deliveryprioritycode;
    deliveryreceiptrequested: boolean;
    description: string;
    directioncode: boolean;
    emailreminderexpirytime: Date;
    emailreminderstatus: email_reminderstatus;
    emailremindertext: string;
    emailremindertype: email_remindertype;
    emailsender_guid: XQW.Guid;
    emailtrackingid: XQW.Guid;
    exchangerate: any;
    followemailuserpreference: boolean;
    from_guid: XQW.Guid;
    importsequencenumber: number;
    inreplyto: string;
    isbilled: boolean;
    isemailfollowed: boolean;
    isemailreminderset: boolean;
    isregularactivity: boolean;
    isunsafe: number;
    isworkflowcreated: boolean;
    lastonholdtime: Date;
    lastopenedtime: Date;
    linksclickedcount: number;
    messageid: string;
    messageiddupcheck: XQW.Guid;
    mimetype: string;
    modifiedby_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    notifications: email_notifications;
    onholdtime: number;
    opencount: number;
    overriddencreatedon: Date;
    ownerid_guid: XQW.Guid;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    parentactivityid_guid: XQW.Guid;
    postponeemailprocessinguntil: Date;
    prioritycode: email_prioritycode;
    processid: XQW.Guid;
    readreceiptrequested: boolean;
    regardingobjectid_guid: XQW.Guid;
    reminderactioncardid: XQW.Guid;
    replycount: number;
    scheduleddurationminutes: number;
    scheduledend: Date;
    scheduledstart: Date;
    sender: string;
    sendermailboxid_guid: XQW.Guid;
    sendersaccount_guid: XQW.Guid;
    senton: Date;
    slaid_guid: XQW.Guid;
    slainvokedid_guid: XQW.Guid;
    sortdate: Date;
    stageid: XQW.Guid;
    statecode: email_statecode;
    statuscode: email_statuscode;
    subcategory: string;
    subject: string;
    submittedby: string;
    templateid_guid: XQW.Guid;
    timezoneruleversionnumber: number;
    to_guid: XQW.Guid;
    torecipients: string;
    trackingtoken: string;
    transactioncurrencyid_guid: XQW.Guid;
    traversedpath: string;
    utcconversiontimezonecode: number;
    versionnumber: number;
  }
  interface Email_Expand {
    activityid_activitypointer: WebExpand<Email_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
    createdby_email: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { createdby_email: SystemUser_Result }>;
    createdonbehalfby_email: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_email: SystemUser_Result }>;
    email_activity_parties: WebExpand<Email_Expand, ActivityParty_Select, ActivityParty_Filter, { email_activity_parties: ActivityParty_Result[] }>;
    email_connections1: WebExpand<Email_Expand, Connection_Select, Connection_Filter, { email_connections1: Connection_Result[] }>;
    email_connections2: WebExpand<Email_Expand, Connection_Select, Connection_Filter, { email_connections2: Connection_Result[] }>;
    email_email_parentactivityid: WebExpand<Email_Expand, Email_Select, Email_Filter, { email_email_parentactivityid: Email_Result[] }>;
    emailsender_account: WebExpand<Email_Expand, Account_Select, Account_Filter, { emailsender_account: Account_Result }>;
    emailsender_contact: WebExpand<Email_Expand, Contact_Select, Contact_Filter, { emailsender_contact: Contact_Result }>;
    emailsender_systemuser: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { emailsender_systemuser: SystemUser_Result }>;
    modifiedby_email: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_email: SystemUser_Result }>;
    modifiedonbehalfby_email: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_email: SystemUser_Result }>;
    owninguser_email: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_email: SystemUser_Result }>;
    parentactivityid: WebExpand<Email_Expand, Email_Select, Email_Filter, { parentactivityid: Email_Result }>;
    regardingobjectid_account_email: WebExpand<Email_Expand, Account_Select, Account_Filter, { regardingobjectid_account_email: Account_Result }>;
    regardingobjectid_contact_email: WebExpand<Email_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_email: Contact_Result }>;
    sendersaccount: WebExpand<Email_Expand, Account_Select, Account_Filter, { sendersaccount: Account_Result }>;
  }
  interface Email_FormattedResult {
    actualend_formatted?: string;
    actualstart_formatted?: string;
    bcc_formatted?: string;
    cc_formatted?: string;
    correlationmethod_formatted?: string;
    createdby_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    delayedemailsendtime_formatted?: string;
    deliveryprioritycode_formatted?: string;
    emailreminderexpirytime_formatted?: string;
    emailreminderstatus_formatted?: string;
    emailremindertype_formatted?: string;
    emailsender_formatted?: string;
    from_formatted?: string;
    lastonholdtime_formatted?: string;
    lastopenedtime_formatted?: string;
    modifiedby_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    notifications_formatted?: string;
    overriddencreatedon_formatted?: string;
    ownerid_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    parentactivityid_formatted?: string;
    postponeemailprocessinguntil_formatted?: string;
    prioritycode_formatted?: string;
    regardingobjectid_formatted?: string;
    scheduledend_formatted?: string;
    scheduledstart_formatted?: string;
    sendermailboxid_formatted?: string;
    sendersaccount_formatted?: string;
    senton_formatted?: string;
    slaid_formatted?: string;
    slainvokedid_formatted?: string;
    sortdate_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
    templateid_formatted?: string;
    to_formatted?: string;
    transactioncurrencyid_formatted?: string;
  }
  interface Email_Result extends Email_Base, Email_Relationships {
    "@odata.etag": string;
    bcc_guid: string | null;
    cc_guid: string | null;
    createdby_guid: string | null;
    createdonbehalfby_guid: string | null;
    emailsender_guid: string | null;
    from_guid: string | null;
    modifiedby_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
    parentactivityid_guid: string | null;
    regardingobjectid_guid: string | null;
    sendermailboxid_guid: string | null;
    sendersaccount_guid: string | null;
    slaid_guid: string | null;
    slainvokedid_guid: string | null;
    templateid_guid: string | null;
    to_guid: string | null;
    transactioncurrencyid_guid: string | null;
  }
  interface Email_RelatedOne {
    activityid_activitypointer: WebMappingRetrieve<Web.ActivityPointer_Select,Web.ActivityPointer_Expand,Web.ActivityPointer_Filter,Web.ActivityPointer_Fixed,Web.ActivityPointer_Result,Web.ActivityPointer_FormattedResult>;
    createdby_email: WebMappingRetrieve<Web.SystemUser_Select,Web.SystemUser_Expand,Web.SystemUser_Filter,Web.SystemUser_Fixed,Web.SystemUser_Result,Web.SystemUser_FormattedResult>;
    createdonbehalfby_email: WebMappingRetrieve<Web.SystemUser_Select,Web.SystemUser_Expand,Web.SystemUser_Filter,Web.SystemUser_Fixed,Web.SystemUser_Result,Web.SystemUser_FormattedResult>;
    emailsender_account: WebMappingRetrieve<Web.Account_Select,Web.Account_Expand,Web.Account_Filter,Web.Account_Fixed,Web.Account_Result,Web.Account_FormattedResult>;
    emailsender_contact: WebMappingRetrieve<Web.Contact_Select,Web.Contact_Expand,Web.Contact_Filter,Web.Contact_Fixed,Web.Contact_Result,Web.Contact_FormattedResult>;
    emailsender_systemuser: WebMappingRetrieve<Web.SystemUser_Select,Web.SystemUser_Expand,Web.SystemUser_Filter,Web.SystemUser_Fixed,Web.SystemUser_Result,Web.SystemUser_FormattedResult>;
    modifiedby_email: WebMappingRetrieve<Web.SystemUser_Select,Web.SystemUser_Expand,Web.SystemUser_Filter,Web.SystemUser_Fixed,Web.SystemUser_Result,Web.SystemUser_FormattedResult>;
    modifiedonbehalfby_email: WebMappingRetrieve<Web.SystemUser_Select,Web.SystemUser_Expand,Web.SystemUser_Filter,Web.SystemUser_Fixed,Web.SystemUser_Result,Web.SystemUser_FormattedResult>;
    owninguser_email: WebMappingRetrieve<Web.SystemUser_Select,Web.SystemUser_Expand,Web.SystemUser_Filter,Web.SystemUser_Fixed,Web.SystemUser_Result,Web.SystemUser_FormattedResult>;
    parentactivityid: WebMappingRetrieve<Web.Email_Select,Web.Email_Expand,Web.Email_Filter,Web.Email_Fixed,Web.Email_Result,Web.Email_FormattedResult>;
    regardingobjectid_account_email: WebMappingRetrieve<Web.Account_Select,Web.Account_Expand,Web.Account_Filter,Web.Account_Fixed,Web.Account_Result,Web.Account_FormattedResult>;
    regardingobjectid_contact_email: WebMappingRetrieve<Web.Contact_Select,Web.Contact_Expand,Web.Contact_Filter,Web.Contact_Fixed,Web.Contact_Result,Web.Contact_FormattedResult>;
    sendersaccount: WebMappingRetrieve<Web.Account_Select,Web.Account_Expand,Web.Account_Filter,Web.Account_Fixed,Web.Account_Result,Web.Account_FormattedResult>;
  }
  interface Email_RelatedMany {
    email_activity_parties: WebMappingRetrieve<Web.ActivityParty_Select,Web.ActivityParty_Expand,Web.ActivityParty_Filter,Web.ActivityParty_Fixed,Web.ActivityParty_Result,Web.ActivityParty_FormattedResult>;
    email_connections1: WebMappingRetrieve<Web.Connection_Select,Web.Connection_Expand,Web.Connection_Filter,Web.Connection_Fixed,Web.Connection_Result,Web.Connection_FormattedResult>;
    email_connections2: WebMappingRetrieve<Web.Connection_Select,Web.Connection_Expand,Web.Connection_Filter,Web.Connection_Fixed,Web.Connection_Result,Web.Connection_FormattedResult>;
    email_email_parentactivityid: WebMappingRetrieve<Web.Email_Select,Web.Email_Expand,Web.Email_Filter,Web.Email_Fixed,Web.Email_Result,Web.Email_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  emails: WebMappingRetrieve<Web.Email_Select,Web.Email_Expand,Web.Email_Filter,Web.Email_Fixed,Web.Email_Result,Web.Email_FormattedResult>;
}
interface WebEntitiesRelated {
  emails: WebMappingRelated<Web.Email_RelatedOne,Web.Email_RelatedMany>;
}
interface WebEntitiesCUDA {
  emails: WebMappingCUDA<Web.Email_Create,Web.Email_Update,Web.Email_Select>;
}
