//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace CCMS.Common.PoliceCheckModel
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://police.govt.nz/VettingFile")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://police.govt.nz/VettingFile", IsNullable = false)]
    public partial class VettingFile
    {
        [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/2001/XMLSchema-instance")]
        public string schemaLocation { get; set; } = "http://police.govt.nz/VettingFile VettingFile.xsd ";

        private string agencyField;

        private string fileReferenceField;

        private string fileSequenceField;

        private System.DateTime filePreparationDateField;

        private Request[] requestsField;

        private AgencyData[] agencyDataField;

        /// <remarks/>
        public string agency
        {
            get
            {
                return this.agencyField;
            }
            set
            {
                this.agencyField = value;
            }
        }

        /// <remarks/>
        public string fileReference
        {
            get
            {
                return this.fileReferenceField;
            }
            set
            {
                this.fileReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string fileSequence
        {
            get
            {
                return this.fileSequenceField;
            }
            set
            {
                this.fileSequenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime filePreparationDate
        {
            get
            {
                return this.filePreparationDateField;
            }
            set
            {
                this.filePreparationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("request", IsNullable = false)]
        public Request[] requests
        {
            get
            {
                return this.requestsField;
            }
            set
            {
                this.requestsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable = false)]
        public AgencyData[] agencyData
        {
            get
            {
                return this.agencyDataField;
            }
            set
            {
                this.agencyDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://police.govt.nz/VettingFile")]
    public partial class Request
    {

        private RequestType typeField;

        private bool typeFieldSpecified;

        private string referenceField;

        private string permanentReferenceField;

        private System.DateTime dateSignedField;

        private string roleField;

        private string roleLocationField;

        private Identity applicantField;

        private Identity[] familyMembersField;

        /// <remarks/>
        public RequestType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        /// <remarks/>
        public string permanentReference
        {
            get
            {
                return this.permanentReferenceField;
            }
            set
            {
                this.permanentReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dateSigned
        {
            get
            {
                return this.dateSignedField;
            }
            set
            {
                this.dateSignedField = value;
            }
        }

        /// <remarks/>
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }

        /// <remarks/>
        public string roleLocation
        {
            get
            {
                return this.roleLocationField;
            }
            set
            {
                this.roleLocationField = value;
            }
        }

        /// <remarks/>
        public Identity applicant
        {
            get
            {
                return this.applicantField;
            }
            set
            {
                this.applicantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("familyMember", IsNullable = false)]
        public Identity[] familyMembers
        {
            get
            {
                return this.familyMembersField;
            }
            set
            {
                this.familyMembersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://police.govt.nz/VettingFile")]
    public enum RequestType
    {

        /// <remarks/>
        exception,

        /// <remarks/>
        cleanslate,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://police.govt.nz/VettingFile")]
    public partial class Identity
    {

        private IdentityRelationship relationshipField;

        private string driversLicenceNumberField;

        private Name nameField;

        private Name[] otherNamesField;

        private IdentityGender genderField;

        private System.DateTime dateOfBirthField;

        private Address addressField;

        private string placeOfBirthField;

        private string nationalityField;

        /// <remarks/>
        public IdentityRelationship relationship
        {
            get
            {
                return this.relationshipField;
            }
            set
            {
                this.relationshipField = value;
            }
        }

        /// <remarks/>
        public string driversLicenceNumber
        {
            get
            {
                return this.driversLicenceNumberField;
            }
            set
            {
                this.driversLicenceNumberField = value;
            }
        }

        /// <remarks/>
        public Name name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("otherNames")]
        public Name[] otherNames
        {
            get
            {
                return this.otherNamesField;
            }
            set
            {
                this.otherNamesField = value;
            }
        }

        /// <remarks/>
        public IdentityGender gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }

        /// <remarks/>
        public Address address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string placeOfBirth
        {
            get
            {
                return this.placeOfBirthField;
            }
            set
            {
                this.placeOfBirthField = value;
            }
        }

        /// <remarks/>
        public string nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://police.govt.nz/VettingFile")]
    public enum IdentityRelationship
    {

        /// <remarks/>
        applicant,

        /// <remarks/>
        partner,

        /// <remarks/>
        mother,

        /// <remarks/>
        father,

        /// <remarks/>
        brother,

        /// <remarks/>
        sister,

        /// <remarks/>
        child,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://police.govt.nz/VettingFile")]
    public partial class Name
    {

        private NameNameType nameTypeField;

        private bool nameTypeFieldSpecified;

        private string familyNameField;

        private string firstNameField;

        private string middleNamesField;

        private System.DateTime altDobField;

        private bool altDobFieldSpecified;

        /// <remarks/>
        public NameNameType nameType
        {
            get
            {
                return this.nameTypeField;
            }
            set
            {
                this.nameTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nameTypeSpecified
        {
            get
            {
                return this.nameTypeFieldSpecified;
            }
            set
            {
                this.nameTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string familyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }

        /// <remarks/>
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string middleNames
        {
            get
            {
                return this.middleNamesField;
            }
            set
            {
                this.middleNamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime altDob
        {
            get
            {
                return this.altDobField;
            }
            set
            {
                this.altDobField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool altDobSpecified
        {
            get
            {
                return this.altDobFieldSpecified;
            }
            set
            {
                this.altDobFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://police.govt.nz/VettingFile")]
    public enum NameNameType
    {

        /// <remarks/>
        main,

        /// <remarks/>
        alias,

        /// <remarks/>
        maiden,

        /// <remarks/>
        married,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://police.govt.nz/VettingFile")]
    public partial class AgencyData
    {

        private string idField;

        private string valueField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://police.govt.nz/VettingFile")]
    public partial class Address
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detailed", typeof(AddressDetailed))]
        [System.Xml.Serialization.XmlElementAttribute("simple", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://police.govt.nz/VettingFile")]
    public partial class AddressDetailed
    {

        private string line1Field;

        private string line2Field;

        private string line3Field;

        private string suburbField;

        private string townCityField;

        private string postcodeField;

        private string countryField;

        /// <remarks/>
        public string line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }

        /// <remarks/>
        public string line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }

        /// <remarks/>
        public string line3
        {
            get
            {
                return this.line3Field;
            }
            set
            {
                this.line3Field = value;
            }
        }

        /// <remarks/>
        public string suburb
        {
            get
            {
                return this.suburbField;
            }
            set
            {
                this.suburbField = value;
            }
        }

        /// <remarks/>
        public string townCity
        {
            get
            {
                return this.townCityField;
            }
            set
            {
                this.townCityField = value;
            }
        }

        /// <remarks/>
        public string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }

        /// <remarks/>
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://police.govt.nz/VettingFile")]
    public enum IdentityGender
    {

        /// <remarks/>
        male,

        /// <remarks/>
        female,

        /// <remarks/>
        unknown,

        /// <remarks/>
        indeterminate,
    }
}
