//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.XrmContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace Entities {
    
    
    /// <summary>
    /// <para>Display Name: Debt</para>
    /// </summary>
    [EntityLogicalName("dia_debt")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class dia_debt : ExtendedEntity<dia_debtState, dia_debt_statuscode> {
        
        public const string EntityLogicalName = "dia_debt";
        
        public const int EntityTypeCode = 10333;
        
        public dia_debt() : 
                base(EntityLogicalName) {
        }
        
        public dia_debt(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay("dia_name");
            }
        }
        
        [AttributeLogicalName("dia_debtid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("dia_debtid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for entity instances</para>
        /// <para>Display Name: Debt</para>
        /// </summary>
        [AttributeLogicalName("dia_debtid")]
        public Guid? dia_debtId {
            get {
                return GetAttributeValue<Guid?>("dia_debtid");
            }
            set {
                SetId("dia_debtid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who created the record.</para>
        /// <para>Display Name: Created By</para>
        /// </summary>
        [AttributeLogicalName("createdby")]
        public EntityReference CreatedBy {
            get {
                return GetAttributeValue<EntityReference>("createdby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was created.</para>
        /// <para>Display Name: Created On</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        public DateTime? CreatedOn {
            get {
                return GetAttributeValue<DateTime?>("createdon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who created the record.</para>
        /// <para>Display Name: Created By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfby")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("createdonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Exchange rate for the currency associated with the entity with respect to the base currency.</para>
        /// <para>Display Name: Exchange Rate</para>
        /// </summary>
        [AttributeLogicalName("exchangerate")]
        public decimal? ExchangeRate {
            get {
                return GetAttributeValue<decimal?>("exchangerate");
            }
        }
        
        /// <summary>
        /// <para>Sequence number of the import that created this record.</para>
        /// <para>Display Name: Import Sequence Number</para>
        /// </summary>
        [AttributeLogicalName("importsequencenumber")]
        public int? ImportSequenceNumber {
            get {
                return GetAttributeValue<int?>("importsequencenumber");
            }
            set {
                SetAttributeValue("importsequencenumber", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who modified the record.</para>
        /// <para>Display Name: Modified By</para>
        /// </summary>
        [AttributeLogicalName("modifiedby")]
        public EntityReference ModifiedBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was modified.</para>
        /// <para>Display Name: Modified On</para>
        /// </summary>
        [AttributeLogicalName("modifiedon")]
        public DateTime? ModifiedOn {
            get {
                return GetAttributeValue<DateTime?>("modifiedon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who modified the record.</para>
        /// <para>Display Name: Modified By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfby")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Date and time that the record was migrated.</para>
        /// <para>Display Name: Record Created On</para>
        /// </summary>
        [AttributeLogicalName("overriddencreatedon")]
        public DateTime? OverriddenCreatedOn {
            get {
                return GetAttributeValue<DateTime?>("overriddencreatedon");
            }
            set {
                SetAttributeValue("overriddencreatedon", value);
            }
        }
        
        /// <summary>
        /// <para>Owner Id</para>
        /// <para>Display Name: Owner</para>
        /// </summary>
        [AttributeLogicalName("ownerid")]
        public EntityReference OwnerId {
            get {
                return GetAttributeValue<EntityReference>("ownerid");
            }
            set {
                SetAttributeValue("ownerid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the business unit that owns the record</para>
        /// <para>Display Name: Owning Business Unit</para>
        /// </summary>
        [AttributeLogicalName("owningbusinessunit")]
        public EntityReference OwningBusinessUnit {
            get {
                return GetAttributeValue<EntityReference>("owningbusinessunit");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the team that owns the record.</para>
        /// <para>Display Name: Owning Team</para>
        /// </summary>
        [AttributeLogicalName("owningteam")]
        public EntityReference OwningTeam {
            get {
                return GetAttributeValue<EntityReference>("owningteam");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the user that owns the record.</para>
        /// <para>Display Name: Owning User</para>
        /// </summary>
        [AttributeLogicalName("owninguser")]
        public EntityReference OwningUser {
            get {
                return GetAttributeValue<EntityReference>("owninguser");
            }
        }
        
        /// <summary>
        /// <para>For internal use only.</para>
        /// <para>Display Name: Time Zone Rule Version Number</para>
        /// </summary>
        [AttributeLogicalName("timezoneruleversionnumber")]
        public int? TimeZoneRuleVersionNumber {
            get {
                return GetAttributeValue<int?>("timezoneruleversionnumber");
            }
            set {
                SetAttributeValue("timezoneruleversionnumber", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the currency associated with the entity.</para>
        /// <para>Display Name: Currency</para>
        /// </summary>
        [AttributeLogicalName("transactioncurrencyid")]
        public EntityReference TransactionCurrencyId {
            get {
                return GetAttributeValue<EntityReference>("transactioncurrencyid");
            }
            set {
                SetAttributeValue("transactioncurrencyid", value);
            }
        }
        
        /// <summary>
        /// <para>Time zone code that was in use when the record was created.</para>
        /// <para>Display Name: UTC Conversion Time Zone Code</para>
        /// </summary>
        [AttributeLogicalName("utcconversiontimezonecode")]
        public int? UTCConversionTimeZoneCode {
            get {
                return GetAttributeValue<int?>("utcconversiontimezonecode");
            }
            set {
                SetAttributeValue("utcconversiontimezonecode", value);
            }
        }
        
        /// <summary>
        /// <para>Version Number</para>
        /// <para>Display Name: Version Number</para>
        /// </summary>
        [AttributeLogicalName("versionnumber")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        /// <summary>
        /// <para>Display Name: Agency the debt is with</para>
        /// </summary>
        [AttributeLogicalName("dia_agencythedebtiswith")]
        public string dia_agencythedebtiswith {
            get {
                return GetAttributeValue<string>("dia_agencythedebtiswith");
            }
            set {
                SetAttributeValue("dia_agencythedebtiswith", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Amount returned/to return</para>
        /// </summary>
        [AttributeLogicalName("dia_amountreturnedtoreturn")]
        public decimal? dia_amountreturnedtoreturn {
            get {
                return GetMoneyValue("dia_amountreturnedtoreturn");
            }
            set {
                SetMoneyValue("dia_amountreturnedtoreturn", value);
            }
        }
        
        /// <summary>
        /// <para>Value of the Amount returned/to return in base currency.</para>
        /// <para>Display Name: Amount returned/to return (Base)</para>
        /// </summary>
        [AttributeLogicalName("dia_amountreturnedtoreturn_base")]
        public decimal? dia_amountreturnedtoreturn_Base {
            get {
                return GetMoneyValue("dia_amountreturnedtoreturn_base");
            }
        }
        
        /// <summary>
        /// <para>Display Name: CBG application</para>
        /// </summary>
        [AttributeLogicalName("dia_cbgapplicationid")]
        public EntityReference dia_cbgapplicationid {
            get {
                return GetAttributeValue<EntityReference>("dia_cbgapplicationid");
            }
            set {
                SetAttributeValue("dia_cbgapplicationid", value);
            }
        }
        
        /// <summary>
        /// <para>The name of the custom entity.</para>
        /// <para>Display Name: Name</para>
        /// </summary>
        [AttributeLogicalName("dia_name")]
        public string dia_name {
            get {
                return GetAttributeValue<string>("dia_name");
            }
            set {
                SetAttributeValue("dia_name", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Paid back/payment plan</para>
        /// </summary>
        [AttributeLogicalName("dia_paidbackpaymentplan")]
        public dia_yesno? dia_paidbackpaymentplan {
            get {
                return GetOptionSetValue<dia_yesno>("dia_paidbackpaymentplan");
            }
            set {
                SetOptionSetValue("dia_paidbackpaymentplan", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Year debt incurred</para>
        /// </summary>
        [AttributeLogicalName("dia_yeardebtincurred")]
        public string dia_yeardebtincurred {
            get {
                return GetAttributeValue<string>("dia_yeardebtincurred");
            }
            set {
                SetAttributeValue("dia_yeardebtincurred", value);
            }
        }
        
        /// <summary>
        /// <para>Status of the Debt</para>
        /// <para>Display Name: State</para>
        /// </summary>
        [AttributeLogicalName("statecode")]
        public dia_debtState? statecode {
            get {
                return GetOptionSetValue<dia_debtState>("statecode");
            }
            set {
                SetOptionSetValue("statecode", value);
            }
        }
        
        /// <summary>
        /// <para>Reason for the status of the Debt</para>
        /// <para>Display Name: Status</para>
        /// </summary>
        [AttributeLogicalName("statuscode")]
        public dia_debt_statuscode? statuscode {
            get {
                return GetOptionSetValue<dia_debt_statuscode>("statuscode");
            }
            set {
                SetOptionSetValue("statuscode", value);
            }
        }
        
        [AttributeLogicalName("owningbusinessunit")]
        [RelationshipSchemaName("business_unit_dia_debt")]
        public BusinessUnit business_unit_dia_debt {
            get {
                return GetRelatedEntity<BusinessUnit>("business_unit_dia_debt", null);
            }
            set {
                SetRelatedEntity("business_unit_dia_debt", null, value);
            }
        }
        
        [AttributeLogicalName("dia_cbgapplicationid")]
        [RelationshipSchemaName("dia_cbgapplication_debt_cbgapplicationid")]
        public dia_cbgapplication dia_cbgapplication_debt_cbgapplicationid {
            get {
                return GetRelatedEntity<dia_cbgapplication>("dia_cbgapplication_debt_cbgapplicationid", null);
            }
            set {
                SetRelatedEntity("dia_cbgapplication_debt_cbgapplicationid", null, value);
            }
        }
        
        [AttributeLogicalName("createdby")]
        [RelationshipSchemaName("lk_dia_debt_createdby")]
        public SystemUser lk_dia_debt_createdby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_debt_createdby", null);
            }
            set {
                SetRelatedEntity("lk_dia_debt_createdby", null, value);
            }
        }
        
        [AttributeLogicalName("createdonbehalfby")]
        [RelationshipSchemaName("lk_dia_debt_createdonbehalfby")]
        public SystemUser lk_dia_debt_createdonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_debt_createdonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_dia_debt_createdonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedby")]
        [RelationshipSchemaName("lk_dia_debt_modifiedby")]
        public SystemUser lk_dia_debt_modifiedby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_debt_modifiedby", null);
            }
            set {
                SetRelatedEntity("lk_dia_debt_modifiedby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedonbehalfby")]
        [RelationshipSchemaName("lk_dia_debt_modifiedonbehalfby")]
        public SystemUser lk_dia_debt_modifiedonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_debt_modifiedonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_dia_debt_modifiedonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("owningteam")]
        [RelationshipSchemaName("team_dia_debt")]
        public Team team_dia_debt {
            get {
                return GetRelatedEntity<Team>("team_dia_debt", null);
            }
            set {
                SetRelatedEntity("team_dia_debt", null, value);
            }
        }
        
        [AttributeLogicalName("owninguser")]
        [RelationshipSchemaName("user_dia_debt")]
        public SystemUser user_dia_debt {
            get {
                return GetRelatedEntity<SystemUser>("user_dia_debt", null);
            }
            set {
                SetRelatedEntity("user_dia_debt", null, value);
            }
        }
        
        public static dia_debt Retrieve(IOrganizationService service, Guid id, params Expression<Func<dia_debt,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
    
    [DataContract()]
    public enum dia_debtState {
        
        [EnumMember()]
        Active = 0,
        
        [EnumMember()]
        Inactive = 1,
    }
    
    [DataContract()]
    public enum dia_debt_statuscode {
        
        [EnumMember()]
        Active = 1,
        
        [EnumMember()]
        Inactive = 2,
    }
}
