//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.XrmContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace Entities {
    
    
    [EntityLogicalName("dia_cbgapplication_country_currentcitizen")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class dia_cbgapplication_country_currentcitizen : ExtendedEntity<EmptyEnum, EmptyEnum> {
        
        public const string EntityLogicalName = "dia_cbgapplication_country_currentcitizen";
        
        public const int EntityTypeCode = 10368;
        
        public dia_cbgapplication_country_currentcitizen() : 
                base(EntityLogicalName) {
        }
        
        public dia_cbgapplication_country_currentcitizen(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay(null);
            }
        }
        
        [AttributeLogicalName("dia_cbgapplication_country_currentcitizenid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("dia_cbgapplication_country_currentcitizenid", value);
            }
        }
        
        [AttributeLogicalName("dia_cbgapplication_country_currentcitizenid")]
        public Guid? dia_cbgapplication_country_currentcitizenId {
            get {
                return GetAttributeValue<Guid?>("dia_cbgapplication_country_currentcitizenid");
            }
            set {
                SetId("dia_cbgapplication_country_currentcitizenid", value);
            }
        }
        
        [AttributeLogicalName("versionnumber")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        [AttributeLogicalName("dia_cbgapplicationid")]
        public Guid? dia_cbgapplicationid {
            get {
                return GetAttributeValue<Guid?>("dia_cbgapplicationid");
            }
        }
        
        [AttributeLogicalName("dia_countryid")]
        public Guid? dia_countryid {
            get {
                return GetAttributeValue<Guid?>("dia_countryid");
            }
        }
        
        public static dia_cbgapplication_country_currentcitizen Retrieve(IOrganizationService service, Guid id, params Expression<Func<dia_cbgapplication_country_currentcitizen,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
}
