//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.XrmContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace Entities {
    
    
    /// <summary>
    /// <para>Allows a user to record marriages and civil unions.</para>
    /// <para>Display Name: Marriages and Civil Unions</para>
    /// </summary>
    [EntityLogicalName("dia_marriagescivilunions")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class dia_marriagescivilunions : ExtendedEntity<dia_marriagescivilunionsState, dia_marriagescivilunions_statuscode> {
        
        public const string EntityLogicalName = "dia_marriagescivilunions";
        
        public const int EntityTypeCode = 10349;
        
        public dia_marriagescivilunions() : 
                base(EntityLogicalName) {
        }
        
        public dia_marriagescivilunions(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay("dia_name");
            }
        }
        
        [AttributeLogicalName("dia_marriagescivilunionsid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("dia_marriagescivilunionsid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for entity instances</para>
        /// <para>Display Name: Marriages and Civil Unions</para>
        /// </summary>
        [AttributeLogicalName("dia_marriagescivilunionsid")]
        public Guid? dia_marriagescivilunionsId {
            get {
                return GetAttributeValue<Guid?>("dia_marriagescivilunionsid");
            }
            set {
                SetId("dia_marriagescivilunionsid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who created the record.</para>
        /// <para>Display Name: Created By</para>
        /// </summary>
        [AttributeLogicalName("createdby")]
        public EntityReference CreatedBy {
            get {
                return GetAttributeValue<EntityReference>("createdby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was created.</para>
        /// <para>Display Name: Created On</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        public DateTime? CreatedOn {
            get {
                return GetAttributeValue<DateTime?>("createdon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who created the record.</para>
        /// <para>Display Name: Created By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfby")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("createdonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Sequence number of the import that created this record.</para>
        /// <para>Display Name: Import Sequence Number</para>
        /// </summary>
        [AttributeLogicalName("importsequencenumber")]
        public int? ImportSequenceNumber {
            get {
                return GetAttributeValue<int?>("importsequencenumber");
            }
            set {
                SetAttributeValue("importsequencenumber", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who modified the record.</para>
        /// <para>Display Name: Modified By</para>
        /// </summary>
        [AttributeLogicalName("modifiedby")]
        public EntityReference ModifiedBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was modified.</para>
        /// <para>Display Name: Modified On</para>
        /// </summary>
        [AttributeLogicalName("modifiedon")]
        public DateTime? ModifiedOn {
            get {
                return GetAttributeValue<DateTime?>("modifiedon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who modified the record.</para>
        /// <para>Display Name: Modified By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfby")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Date and time that the record was migrated.</para>
        /// <para>Display Name: Record Created On</para>
        /// </summary>
        [AttributeLogicalName("overriddencreatedon")]
        public DateTime? OverriddenCreatedOn {
            get {
                return GetAttributeValue<DateTime?>("overriddencreatedon");
            }
            set {
                SetAttributeValue("overriddencreatedon", value);
            }
        }
        
        /// <summary>
        /// <para>Owner Id</para>
        /// <para>Display Name: Owner</para>
        /// </summary>
        [AttributeLogicalName("ownerid")]
        public EntityReference OwnerId {
            get {
                return GetAttributeValue<EntityReference>("ownerid");
            }
            set {
                SetAttributeValue("ownerid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the business unit that owns the record</para>
        /// <para>Display Name: Owning Business Unit</para>
        /// </summary>
        [AttributeLogicalName("owningbusinessunit")]
        public EntityReference OwningBusinessUnit {
            get {
                return GetAttributeValue<EntityReference>("owningbusinessunit");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the team that owns the record.</para>
        /// <para>Display Name: Owning Team</para>
        /// </summary>
        [AttributeLogicalName("owningteam")]
        public EntityReference OwningTeam {
            get {
                return GetAttributeValue<EntityReference>("owningteam");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the user that owns the record.</para>
        /// <para>Display Name: Owning User</para>
        /// </summary>
        [AttributeLogicalName("owninguser")]
        public EntityReference OwningUser {
            get {
                return GetAttributeValue<EntityReference>("owninguser");
            }
        }
        
        /// <summary>
        /// <para>For internal use only.</para>
        /// <para>Display Name: Time Zone Rule Version Number</para>
        /// </summary>
        [AttributeLogicalName("timezoneruleversionnumber")]
        public int? TimeZoneRuleVersionNumber {
            get {
                return GetAttributeValue<int?>("timezoneruleversionnumber");
            }
            set {
                SetAttributeValue("timezoneruleversionnumber", value);
            }
        }
        
        /// <summary>
        /// <para>Time zone code that was in use when the record was created.</para>
        /// <para>Display Name: UTC Conversion Time Zone Code</para>
        /// </summary>
        [AttributeLogicalName("utcconversiontimezonecode")]
        public int? UTCConversionTimeZoneCode {
            get {
                return GetAttributeValue<int?>("utcconversiontimezonecode");
            }
            set {
                SetAttributeValue("utcconversiontimezonecode", value);
            }
        }
        
        /// <summary>
        /// <para>Version Number</para>
        /// <para>Display Name: Version Number</para>
        /// </summary>
        [AttributeLogicalName("versionnumber")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        /// <summary>
        /// <para>Display Name: CBG application</para>
        /// </summary>
        [AttributeLogicalName("dia_cbgapplicationid")]
        public EntityReference dia_cbgapplicationid {
            get {
                return GetAttributeValue<EntityReference>("dia_cbgapplicationid");
            }
            set {
                SetAttributeValue("dia_cbgapplicationid", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Married in NZ</para>
        /// </summary>
        [AttributeLogicalName("dia_marriedinnz")]
        public dia_yesno? dia_marriedinnz {
            get {
                return GetOptionSetValue<dia_yesno>("dia_marriedinnz");
            }
            set {
                SetOptionSetValue("dia_marriedinnz", value);
            }
        }
        
        /// <summary>
        /// <para>The name of the custom entity.</para>
        /// <para>Display Name: Name</para>
        /// </summary>
        [AttributeLogicalName("dia_name")]
        public string dia_name {
            get {
                return GetAttributeValue<string>("dia_name");
            }
            set {
                SetAttributeValue("dia_name", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Spouse family name before marriage</para>
        /// </summary>
        [AttributeLogicalName("dia_spousefamilynamebeforemarriage")]
        public string dia_spousefamilynamebeforemarriage {
            get {
                return GetAttributeValue<string>("dia_spousefamilynamebeforemarriage");
            }
            set {
                SetAttributeValue("dia_spousefamilynamebeforemarriage", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Spouse given names</para>
        /// </summary>
        [AttributeLogicalName("dia_spousegivenname")]
        public string dia_spousegivenname {
            get {
                return GetAttributeValue<string>("dia_spousegivenname");
            }
            set {
                SetAttributeValue("dia_spousegivenname", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Year of marriage/civil union</para>
        /// </summary>
        [AttributeLogicalName("dia_yearofmarriagecivilunion")]
        public string dia_yearofmarriagecivilunion {
            get {
                return GetAttributeValue<string>("dia_yearofmarriagecivilunion");
            }
            set {
                SetAttributeValue("dia_yearofmarriagecivilunion", value);
            }
        }
        
        /// <summary>
        /// <para>Status of the Marriages and Civil Unions</para>
        /// <para>Display Name: State</para>
        /// </summary>
        [AttributeLogicalName("statecode")]
        public dia_marriagescivilunionsState? statecode {
            get {
                return GetOptionSetValue<dia_marriagescivilunionsState>("statecode");
            }
            set {
                SetOptionSetValue("statecode", value);
            }
        }
        
        /// <summary>
        /// <para>Reason for the status of the Marriages and Civil Unions</para>
        /// <para>Display Name: Status</para>
        /// </summary>
        [AttributeLogicalName("statuscode")]
        public dia_marriagescivilunions_statuscode? statuscode {
            get {
                return GetOptionSetValue<dia_marriagescivilunions_statuscode>("statuscode");
            }
            set {
                SetOptionSetValue("statuscode", value);
            }
        }
        
        [AttributeLogicalName("owningbusinessunit")]
        [RelationshipSchemaName("business_unit_dia_marriagescivilunions")]
        public BusinessUnit business_unit_dia_marriagescivilunions {
            get {
                return GetRelatedEntity<BusinessUnit>("business_unit_dia_marriagescivilunions", null);
            }
            set {
                SetRelatedEntity("business_unit_dia_marriagescivilunions", null, value);
            }
        }
        
        [AttributeLogicalName("dia_cbgapplicationid")]
        [RelationshipSchemaName("dia_cbgapplication_marriagescivilunions_cbgapplicationid")]
        public dia_cbgapplication dia_cbgapplication_marriagescivilunions_cbgapplicationid {
            get {
                return GetRelatedEntity<dia_cbgapplication>("dia_cbgapplication_marriagescivilunions_cbgapplicationid", null);
            }
            set {
                SetRelatedEntity("dia_cbgapplication_marriagescivilunions_cbgapplicationid", null, value);
            }
        }
        
        [AttributeLogicalName("createdby")]
        [RelationshipSchemaName("lk_dia_marriagescivilunions_createdby")]
        public SystemUser lk_dia_marriagescivilunions_createdby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_marriagescivilunions_createdby", null);
            }
            set {
                SetRelatedEntity("lk_dia_marriagescivilunions_createdby", null, value);
            }
        }
        
        [AttributeLogicalName("createdonbehalfby")]
        [RelationshipSchemaName("lk_dia_marriagescivilunions_createdonbehalfby")]
        public SystemUser lk_dia_marriagescivilunions_createdonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_marriagescivilunions_createdonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_dia_marriagescivilunions_createdonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedby")]
        [RelationshipSchemaName("lk_dia_marriagescivilunions_modifiedby")]
        public SystemUser lk_dia_marriagescivilunions_modifiedby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_marriagescivilunions_modifiedby", null);
            }
            set {
                SetRelatedEntity("lk_dia_marriagescivilunions_modifiedby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedonbehalfby")]
        [RelationshipSchemaName("lk_dia_marriagescivilunions_modifiedonbehalfby")]
        public SystemUser lk_dia_marriagescivilunions_modifiedonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_marriagescivilunions_modifiedonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_dia_marriagescivilunions_modifiedonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("owningteam")]
        [RelationshipSchemaName("team_dia_marriagescivilunions")]
        public Team team_dia_marriagescivilunions {
            get {
                return GetRelatedEntity<Team>("team_dia_marriagescivilunions", null);
            }
            set {
                SetRelatedEntity("team_dia_marriagescivilunions", null, value);
            }
        }
        
        [AttributeLogicalName("owninguser")]
        [RelationshipSchemaName("user_dia_marriagescivilunions")]
        public SystemUser user_dia_marriagescivilunions {
            get {
                return GetRelatedEntity<SystemUser>("user_dia_marriagescivilunions", null);
            }
            set {
                SetRelatedEntity("user_dia_marriagescivilunions", null, value);
            }
        }
        
        public static dia_marriagescivilunions Retrieve(IOrganizationService service, Guid id, params Expression<Func<dia_marriagescivilunions,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
    
    [DataContract()]
    public enum dia_marriagescivilunionsState {
        
        [EnumMember()]
        Active = 0,
        
        [EnumMember()]
        Inactive = 1,
    }
    
    [DataContract()]
    public enum dia_marriagescivilunions_statuscode {
        
        [EnumMember()]
        Active = 1,
        
        [EnumMember()]
        Inactive = 2,
    }
}
