//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.XrmContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace Entities {
    
    
    [EntityLogicalName("dia_country_cbgapplication_parent1")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class dia_country_cbgapplication_parent1 : ExtendedEntity<EmptyEnum, EmptyEnum> {
        
        public const string EntityLogicalName = "dia_country_cbgapplication_parent1";
        
        public const int EntityTypeCode = 10370;
        
        public dia_country_cbgapplication_parent1() : 
                base(EntityLogicalName) {
        }
        
        public dia_country_cbgapplication_parent1(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay(null);
            }
        }
        
        [AttributeLogicalName("dia_country_cbgapplication_parent1id")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("dia_country_cbgapplication_parent1id", value);
            }
        }
        
        [AttributeLogicalName("dia_country_cbgapplication_parent1id")]
        public Guid? dia_country_cbgapplication_parent1Id {
            get {
                return GetAttributeValue<Guid?>("dia_country_cbgapplication_parent1id");
            }
            set {
                SetId("dia_country_cbgapplication_parent1id", value);
            }
        }
        
        [AttributeLogicalName("versionnumber")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        [AttributeLogicalName("dia_cbgapplicationid")]
        public Guid? dia_cbgapplicationid {
            get {
                return GetAttributeValue<Guid?>("dia_cbgapplicationid");
            }
        }
        
        [AttributeLogicalName("dia_countryid")]
        public Guid? dia_countryid {
            get {
                return GetAttributeValue<Guid?>("dia_countryid");
            }
        }
        
        public static dia_country_cbgapplication_parent1 Retrieve(IOrganizationService service, Guid id, params Expression<Func<dia_country_cbgapplication_parent1,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
}
