//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xrm.Sdk.Client;
using System.Runtime.Serialization;

[assembly: ProxyTypesAssembly()]


namespace Entities {
    
    
    [DataContract()]
    public enum dia_yesno {
        
        [EnumMember()]
        Yes = 100000000,
        
        [EnumMember()]
        No = 100000001,
    }
    
    [DataContract()]
    public enum dia_specialceremonytype {
        
        [EnumMember()]
        Private = 100000000,
        
        [EnumMember()]
        Overseas = 100000001,
    }
    
    [DataContract()]
    public enum dia_citizenshipceremonystatement {
        
        [EnumMember()]
        Oath = 100000000,
        
        [EnumMember()]
        Affirmation = 100000001,
    }
    
    [DataContract()]
    public enum dia_livenesschecktype {
        
        [EnumMember()]
        ParentReferee = 100000000,
        
        [EnumMember()]
        Youth1415 = 100000001,
        
        [EnumMember()]
        Adult = 100000002,
    }
    
    [DataContract()]
    public enum incident_caseorigincode {
        
        [EnumMember()]
        Phone = 1,
        
        [EnumMember()]
        Mail = 2,
        
        [EnumMember()]
        Online = 3,
        
        [EnumMember()]
        Counter = 100000000,
    }
    
    [DataContract()]
    public enum socialactivity_postmessagetype {
        
        [EnumMember()]
        PublicMessage = 0,
        
        [EnumMember()]
        PrivateMessage = 1,
    }
    
    [DataContract()]
    public enum servicestage {
        
        [EnumMember()]
        Identify = 0,
        
        [EnumMember()]
        Research = 1,
        
        [EnumMember()]
        Resolve = 2,
    }
}
