declare namespace Rest {
  interface AccountBase extends RestEntity {
    AccountCategoryCode?: SDK.OptionSet<account_accountcategorycode> | null;
    AccountClassificationCode?: SDK.OptionSet<account_accountclassificationcode> | null;
    AccountId?: string | null;
    AccountNumber?: string | null;
    AccountRatingCode?: SDK.OptionSet<account_accountratingcode> | null;
    Address1_AddressId?: string | null;
    Address1_AddressTypeCode?: SDK.OptionSet<account_address1_addresstypecode> | null;
    Address1_City?: string | null;
    Address1_Composite?: string | null;
    Address1_Country?: string | null;
    Address1_County?: string | null;
    Address1_Fax?: string | null;
    Address1_FreightTermsCode?: SDK.OptionSet<account_address1_freighttermscode> | null;
    Address1_Latitude?: number | null;
    Address1_Line1?: string | null;
    Address1_Line2?: string | null;
    Address1_Line3?: string | null;
    Address1_Longitude?: number | null;
    Address1_Name?: string | null;
    Address1_PostOfficeBox?: string | null;
    Address1_PostalCode?: string | null;
    Address1_PrimaryContactName?: string | null;
    Address1_ShippingMethodCode?: SDK.OptionSet<account_address1_shippingmethodcode> | null;
    Address1_StateOrProvince?: string | null;
    Address1_Telephone1?: string | null;
    Address1_Telephone2?: string | null;
    Address1_Telephone3?: string | null;
    Address1_UPSZone?: string | null;
    Address1_UTCOffset?: number | null;
    Address2_AddressId?: string | null;
    Address2_AddressTypeCode?: SDK.OptionSet<account_address2_addresstypecode> | null;
    Address2_City?: string | null;
    Address2_Composite?: string | null;
    Address2_Country?: string | null;
    Address2_County?: string | null;
    Address2_Fax?: string | null;
    Address2_FreightTermsCode?: SDK.OptionSet<account_address2_freighttermscode> | null;
    Address2_Latitude?: number | null;
    Address2_Line1?: string | null;
    Address2_Line2?: string | null;
    Address2_Line3?: string | null;
    Address2_Longitude?: number | null;
    Address2_Name?: string | null;
    Address2_PostOfficeBox?: string | null;
    Address2_PostalCode?: string | null;
    Address2_PrimaryContactName?: string | null;
    Address2_ShippingMethodCode?: SDK.OptionSet<account_address2_shippingmethodcode> | null;
    Address2_StateOrProvince?: string | null;
    Address2_Telephone1?: string | null;
    Address2_Telephone2?: string | null;
    Address2_Telephone3?: string | null;
    Address2_UPSZone?: string | null;
    Address2_UTCOffset?: number | null;
    Adx_CreatedByIPAddress?: string | null;
    Adx_CreatedByUsername?: string | null;
    Adx_ModifiedByIPAddress?: string | null;
    Adx_ModifiedByUsername?: string | null;
    Aging30?: SDK.Money | null;
    Aging30_Base?: SDK.Money | null;
    Aging60?: SDK.Money | null;
    Aging60_Base?: SDK.Money | null;
    Aging90?: SDK.Money | null;
    Aging90_Base?: SDK.Money | null;
    BusinessTypeCode?: SDK.OptionSet<account_businesstypecode> | null;
    CreatedBy?: SDK.EntityReference | null;
    CreatedByExternalParty?: SDK.EntityReference | null;
    CreatedOn?: Date | null;
    CreatedOnBehalfBy?: SDK.EntityReference | null;
    CreditLimit?: SDK.Money | null;
    CreditLimit_Base?: SDK.Money | null;
    CreditOnHold?: boolean | null;
    CustomerSizeCode?: SDK.OptionSet<account_customersizecode> | null;
    CustomerTypeCode?: SDK.OptionSet<account_customertypecode> | null;
    Description?: string | null;
    DoNotBulkEMail?: boolean | null;
    DoNotBulkPostalMail?: boolean | null;
    DoNotEMail?: boolean | null;
    DoNotFax?: boolean | null;
    DoNotPhone?: boolean | null;
    DoNotPostalMail?: boolean | null;
    DoNotSendMM?: boolean | null;
    EMailAddress1?: string | null;
    EMailAddress2?: string | null;
    EMailAddress3?: string | null;
    EntityImageId?: string | null;
    ExchangeRate?: string | null;
    Fax?: string | null;
    FollowEmail?: boolean | null;
    FtpSiteURL?: string | null;
    ImportSequenceNumber?: number | null;
    IndustryCode?: SDK.OptionSet<account_industrycode> | null;
    IsPrivate?: boolean | null;
    LastOnHoldTime?: Date | null;
    LastUsedInCampaign?: Date | null;
    MarketCap?: SDK.Money | null;
    MarketCap_Base?: SDK.Money | null;
    MarketingOnly?: boolean | null;
    MasterId?: SDK.EntityReference | null;
    Merged?: boolean | null;
    ModifiedBy?: SDK.EntityReference | null;
    ModifiedByExternalParty?: SDK.EntityReference | null;
    ModifiedOn?: Date | null;
    ModifiedOnBehalfBy?: SDK.EntityReference | null;
    Name?: string | null;
    NumberOfEmployees?: number | null;
    OnHoldTime?: number | null;
    OverriddenCreatedOn?: Date | null;
    OwnerId?: SDK.EntityReference | null;
    OwnershipCode?: SDK.OptionSet<account_ownershipcode> | null;
    OwningBusinessUnit?: SDK.EntityReference | null;
    OwningTeam?: SDK.EntityReference | null;
    OwningUser?: SDK.EntityReference | null;
    ParentAccountId?: SDK.EntityReference | null;
    ParticipatesInWorkflow?: boolean | null;
    PaymentTermsCode?: SDK.OptionSet<account_paymenttermscode> | null;
    PreferredAppointmentDayCode?: SDK.OptionSet<account_preferredappointmentdaycode> | null;
    PreferredAppointmentTimeCode?: SDK.OptionSet<account_preferredappointmenttimecode> | null;
    PreferredContactMethodCode?: SDK.OptionSet<account_preferredcontactmethodcode> | null;
    PreferredSystemUserId?: SDK.EntityReference | null;
    PrimaryContactId?: SDK.EntityReference | null;
    PrimarySatoriId?: string | null;
    PrimaryTwitterId?: string | null;
    ProcessId?: string | null;
    Revenue?: SDK.Money | null;
    Revenue_Base?: SDK.Money | null;
    SIC?: string | null;
    SLAId?: SDK.EntityReference | null;
    SLAInvokedId?: SDK.EntityReference | null;
    SharesOutstanding?: number | null;
    ShippingMethodCode?: SDK.OptionSet<account_shippingmethodcode> | null;
    StageId?: string | null;
    StateCode?: SDK.OptionSet<account_statecode> | null;
    StatusCode?: SDK.OptionSet<account_statuscode> | null;
    StockExchange?: string | null;
    Telephone1?: string | null;
    Telephone2?: string | null;
    Telephone3?: string | null;
    TerritoryCode?: SDK.OptionSet<account_territorycode> | null;
    TickerSymbol?: string | null;
    TimeSpentByMeOnEmailAndMeetings?: string | null;
    TimeZoneRuleVersionNumber?: number | null;
    TransactionCurrencyId?: SDK.EntityReference | null;
    TraversedPath?: string | null;
    UTCConversionTimeZoneCode?: number | null;
    VersionNumber?: number | null;
    WebSiteURL?: string | null;
    msa_managingpartnerid?: SDK.EntityReference | null;
  }
  interface Account extends AccountBase {
    Account_ActivityPointers?: ActivityPointer[] | null;
    Account_Email_EmailSender?: Email[] | null;
    Account_Email_SendersAccount?: Email[] | null;
    Account_Emails?: Email[] | null;
    Referencedaccount_master_account?: Account[] | null;
    Referencedaccount_parent_account?: Account[] | null;
    Referencedmsa_account_managingpartner?: Account[] | null;
    Referencingaccount_master_account?: Account | null;
    Referencingaccount_parent_account?: Account | null;
    Referencingmsa_account_managingpartner?: Account | null;
    account_activity_parties?: ActivityParty[] | null;
    account_connections1?: Connection[] | null;
    account_connections2?: Connection[] | null;
    account_primary_contact?: Contact | null;
    contact_customer_accounts?: Contact[] | null;
    lk_accountbase_createdby?: SystemUser | null;
    lk_accountbase_createdonbehalfby?: SystemUser | null;
    lk_accountbase_modifiedby?: SystemUser | null;
    lk_accountbase_modifiedonbehalfby?: SystemUser | null;
    msa_contact_managingpartner?: Contact[] | null;
    owner_accounts?: SystemUser | null;
    system_user_accounts?: SystemUser | null;
    user_accounts?: SystemUser | null;
  }
  interface AccountResult extends AccountBase {
    Account_ActivityPointers?: SDK.Results<ActivityPointerResult> | null;
    Account_Email_EmailSender?: SDK.Results<EmailResult> | null;
    Account_Email_SendersAccount?: SDK.Results<EmailResult> | null;
    Account_Emails?: SDK.Results<EmailResult> | null;
    Referencedaccount_master_account?: SDK.Results<AccountResult> | null;
    Referencedaccount_parent_account?: SDK.Results<AccountResult> | null;
    Referencedmsa_account_managingpartner?: SDK.Results<AccountResult> | null;
    Referencingaccount_master_account?: Account | null;
    Referencingaccount_parent_account?: Account | null;
    Referencingmsa_account_managingpartner?: Account | null;
    account_activity_parties?: SDK.Results<ActivityPartyResult> | null;
    account_connections1?: SDK.Results<ConnectionResult> | null;
    account_connections2?: SDK.Results<ConnectionResult> | null;
    account_primary_contact?: Contact | null;
    contact_customer_accounts?: SDK.Results<ContactResult> | null;
    lk_accountbase_createdby?: SystemUser | null;
    lk_accountbase_createdonbehalfby?: SystemUser | null;
    lk_accountbase_modifiedby?: SystemUser | null;
    lk_accountbase_modifiedonbehalfby?: SystemUser | null;
    msa_contact_managingpartner?: SDK.Results<ContactResult> | null;
    owner_accounts?: SystemUser | null;
    system_user_accounts?: SystemUser | null;
    user_accounts?: SystemUser | null;
  }
  interface Account_Select extends Account_Expand {
    AccountCategoryCode: RestAttribute<Account_Select>;
    AccountClassificationCode: RestAttribute<Account_Select>;
    AccountId: RestAttribute<Account_Select>;
    AccountNumber: RestAttribute<Account_Select>;
    AccountRatingCode: RestAttribute<Account_Select>;
    Address1_AddressId: RestAttribute<Account_Select>;
    Address1_AddressTypeCode: RestAttribute<Account_Select>;
    Address1_City: RestAttribute<Account_Select>;
    Address1_Composite: RestAttribute<Account_Select>;
    Address1_Country: RestAttribute<Account_Select>;
    Address1_County: RestAttribute<Account_Select>;
    Address1_Fax: RestAttribute<Account_Select>;
    Address1_FreightTermsCode: RestAttribute<Account_Select>;
    Address1_Latitude: RestAttribute<Account_Select>;
    Address1_Line1: RestAttribute<Account_Select>;
    Address1_Line2: RestAttribute<Account_Select>;
    Address1_Line3: RestAttribute<Account_Select>;
    Address1_Longitude: RestAttribute<Account_Select>;
    Address1_Name: RestAttribute<Account_Select>;
    Address1_PostOfficeBox: RestAttribute<Account_Select>;
    Address1_PostalCode: RestAttribute<Account_Select>;
    Address1_PrimaryContactName: RestAttribute<Account_Select>;
    Address1_ShippingMethodCode: RestAttribute<Account_Select>;
    Address1_StateOrProvince: RestAttribute<Account_Select>;
    Address1_Telephone1: RestAttribute<Account_Select>;
    Address1_Telephone2: RestAttribute<Account_Select>;
    Address1_Telephone3: RestAttribute<Account_Select>;
    Address1_UPSZone: RestAttribute<Account_Select>;
    Address1_UTCOffset: RestAttribute<Account_Select>;
    Address2_AddressId: RestAttribute<Account_Select>;
    Address2_AddressTypeCode: RestAttribute<Account_Select>;
    Address2_City: RestAttribute<Account_Select>;
    Address2_Composite: RestAttribute<Account_Select>;
    Address2_Country: RestAttribute<Account_Select>;
    Address2_County: RestAttribute<Account_Select>;
    Address2_Fax: RestAttribute<Account_Select>;
    Address2_FreightTermsCode: RestAttribute<Account_Select>;
    Address2_Latitude: RestAttribute<Account_Select>;
    Address2_Line1: RestAttribute<Account_Select>;
    Address2_Line2: RestAttribute<Account_Select>;
    Address2_Line3: RestAttribute<Account_Select>;
    Address2_Longitude: RestAttribute<Account_Select>;
    Address2_Name: RestAttribute<Account_Select>;
    Address2_PostOfficeBox: RestAttribute<Account_Select>;
    Address2_PostalCode: RestAttribute<Account_Select>;
    Address2_PrimaryContactName: RestAttribute<Account_Select>;
    Address2_ShippingMethodCode: RestAttribute<Account_Select>;
    Address2_StateOrProvince: RestAttribute<Account_Select>;
    Address2_Telephone1: RestAttribute<Account_Select>;
    Address2_Telephone2: RestAttribute<Account_Select>;
    Address2_Telephone3: RestAttribute<Account_Select>;
    Address2_UPSZone: RestAttribute<Account_Select>;
    Address2_UTCOffset: RestAttribute<Account_Select>;
    Adx_CreatedByIPAddress: RestAttribute<Account_Select>;
    Adx_CreatedByUsername: RestAttribute<Account_Select>;
    Adx_ModifiedByIPAddress: RestAttribute<Account_Select>;
    Adx_ModifiedByUsername: RestAttribute<Account_Select>;
    Aging30: RestAttribute<Account_Select>;
    Aging30_Base: RestAttribute<Account_Select>;
    Aging60: RestAttribute<Account_Select>;
    Aging60_Base: RestAttribute<Account_Select>;
    Aging90: RestAttribute<Account_Select>;
    Aging90_Base: RestAttribute<Account_Select>;
    BusinessTypeCode: RestAttribute<Account_Select>;
    CreatedBy: RestAttribute<Account_Select>;
    CreatedByExternalParty: RestAttribute<Account_Select>;
    CreatedOn: RestAttribute<Account_Select>;
    CreatedOnBehalfBy: RestAttribute<Account_Select>;
    CreditLimit: RestAttribute<Account_Select>;
    CreditLimit_Base: RestAttribute<Account_Select>;
    CreditOnHold: RestAttribute<Account_Select>;
    CustomerSizeCode: RestAttribute<Account_Select>;
    CustomerTypeCode: RestAttribute<Account_Select>;
    Description: RestAttribute<Account_Select>;
    DoNotBulkEMail: RestAttribute<Account_Select>;
    DoNotBulkPostalMail: RestAttribute<Account_Select>;
    DoNotEMail: RestAttribute<Account_Select>;
    DoNotFax: RestAttribute<Account_Select>;
    DoNotPhone: RestAttribute<Account_Select>;
    DoNotPostalMail: RestAttribute<Account_Select>;
    DoNotSendMM: RestAttribute<Account_Select>;
    EMailAddress1: RestAttribute<Account_Select>;
    EMailAddress2: RestAttribute<Account_Select>;
    EMailAddress3: RestAttribute<Account_Select>;
    EntityImageId: RestAttribute<Account_Select>;
    ExchangeRate: RestAttribute<Account_Select>;
    Fax: RestAttribute<Account_Select>;
    FollowEmail: RestAttribute<Account_Select>;
    FtpSiteURL: RestAttribute<Account_Select>;
    ImportSequenceNumber: RestAttribute<Account_Select>;
    IndustryCode: RestAttribute<Account_Select>;
    IsPrivate: RestAttribute<Account_Select>;
    LastOnHoldTime: RestAttribute<Account_Select>;
    LastUsedInCampaign: RestAttribute<Account_Select>;
    MarketCap: RestAttribute<Account_Select>;
    MarketCap_Base: RestAttribute<Account_Select>;
    MarketingOnly: RestAttribute<Account_Select>;
    MasterId: RestAttribute<Account_Select>;
    Merged: RestAttribute<Account_Select>;
    ModifiedBy: RestAttribute<Account_Select>;
    ModifiedByExternalParty: RestAttribute<Account_Select>;
    ModifiedOn: RestAttribute<Account_Select>;
    ModifiedOnBehalfBy: RestAttribute<Account_Select>;
    Name: RestAttribute<Account_Select>;
    NumberOfEmployees: RestAttribute<Account_Select>;
    OnHoldTime: RestAttribute<Account_Select>;
    OverriddenCreatedOn: RestAttribute<Account_Select>;
    OwnerId: RestAttribute<Account_Select>;
    OwnershipCode: RestAttribute<Account_Select>;
    OwningBusinessUnit: RestAttribute<Account_Select>;
    OwningTeam: RestAttribute<Account_Select>;
    OwningUser: RestAttribute<Account_Select>;
    ParentAccountId: RestAttribute<Account_Select>;
    ParticipatesInWorkflow: RestAttribute<Account_Select>;
    PaymentTermsCode: RestAttribute<Account_Select>;
    PreferredAppointmentDayCode: RestAttribute<Account_Select>;
    PreferredAppointmentTimeCode: RestAttribute<Account_Select>;
    PreferredContactMethodCode: RestAttribute<Account_Select>;
    PreferredSystemUserId: RestAttribute<Account_Select>;
    PrimaryContactId: RestAttribute<Account_Select>;
    PrimarySatoriId: RestAttribute<Account_Select>;
    PrimaryTwitterId: RestAttribute<Account_Select>;
    ProcessId: RestAttribute<Account_Select>;
    Revenue: RestAttribute<Account_Select>;
    Revenue_Base: RestAttribute<Account_Select>;
    SIC: RestAttribute<Account_Select>;
    SLAId: RestAttribute<Account_Select>;
    SLAInvokedId: RestAttribute<Account_Select>;
    SharesOutstanding: RestAttribute<Account_Select>;
    ShippingMethodCode: RestAttribute<Account_Select>;
    StageId: RestAttribute<Account_Select>;
    StateCode: RestAttribute<Account_Select>;
    StatusCode: RestAttribute<Account_Select>;
    StockExchange: RestAttribute<Account_Select>;
    Telephone1: RestAttribute<Account_Select>;
    Telephone2: RestAttribute<Account_Select>;
    Telephone3: RestAttribute<Account_Select>;
    TerritoryCode: RestAttribute<Account_Select>;
    TickerSymbol: RestAttribute<Account_Select>;
    TimeSpentByMeOnEmailAndMeetings: RestAttribute<Account_Select>;
    TimeZoneRuleVersionNumber: RestAttribute<Account_Select>;
    TransactionCurrencyId: RestAttribute<Account_Select>;
    TraversedPath: RestAttribute<Account_Select>;
    UTCConversionTimeZoneCode: RestAttribute<Account_Select>;
    VersionNumber: RestAttribute<Account_Select>;
    WebSiteURL: RestAttribute<Account_Select>;
    msa_managingpartnerid: RestAttribute<Account_Select>;
  }
  interface Account_Filter {
    AccountCategoryCode: XQR.ValueContainerFilter<account_accountcategorycode>;
    AccountClassificationCode: XQR.ValueContainerFilter<account_accountclassificationcode>;
    AccountId: XQR.Guid;
    AccountNumber: string;
    AccountRatingCode: XQR.ValueContainerFilter<account_accountratingcode>;
    Address1_AddressId: XQR.Guid;
    Address1_AddressTypeCode: XQR.ValueContainerFilter<account_address1_addresstypecode>;
    Address1_City: string;
    Address1_Composite: string;
    Address1_Country: string;
    Address1_County: string;
    Address1_Fax: string;
    Address1_FreightTermsCode: XQR.ValueContainerFilter<account_address1_freighttermscode>;
    Address1_Latitude: number;
    Address1_Line1: string;
    Address1_Line2: string;
    Address1_Line3: string;
    Address1_Longitude: number;
    Address1_Name: string;
    Address1_PostOfficeBox: string;
    Address1_PostalCode: string;
    Address1_PrimaryContactName: string;
    Address1_ShippingMethodCode: XQR.ValueContainerFilter<account_address1_shippingmethodcode>;
    Address1_StateOrProvince: string;
    Address1_Telephone1: string;
    Address1_Telephone2: string;
    Address1_Telephone3: string;
    Address1_UPSZone: string;
    Address1_UTCOffset: number;
    Address2_AddressId: XQR.Guid;
    Address2_AddressTypeCode: XQR.ValueContainerFilter<account_address2_addresstypecode>;
    Address2_City: string;
    Address2_Composite: string;
    Address2_Country: string;
    Address2_County: string;
    Address2_Fax: string;
    Address2_FreightTermsCode: XQR.ValueContainerFilter<account_address2_freighttermscode>;
    Address2_Latitude: number;
    Address2_Line1: string;
    Address2_Line2: string;
    Address2_Line3: string;
    Address2_Longitude: number;
    Address2_Name: string;
    Address2_PostOfficeBox: string;
    Address2_PostalCode: string;
    Address2_PrimaryContactName: string;
    Address2_ShippingMethodCode: XQR.ValueContainerFilter<account_address2_shippingmethodcode>;
    Address2_StateOrProvince: string;
    Address2_Telephone1: string;
    Address2_Telephone2: string;
    Address2_Telephone3: string;
    Address2_UPSZone: string;
    Address2_UTCOffset: number;
    Adx_CreatedByIPAddress: string;
    Adx_CreatedByUsername: string;
    Adx_ModifiedByIPAddress: string;
    Adx_ModifiedByUsername: string;
    Aging30: XQR.ValueContainerFilter<number>;
    Aging30_Base: XQR.ValueContainerFilter<number>;
    Aging60: XQR.ValueContainerFilter<number>;
    Aging60_Base: XQR.ValueContainerFilter<number>;
    Aging90: XQR.ValueContainerFilter<number>;
    Aging90_Base: XQR.ValueContainerFilter<number>;
    BusinessTypeCode: XQR.ValueContainerFilter<account_businesstypecode>;
    CreatedBy: XQR.EntityReferenceFilter;
    CreatedByExternalParty: XQR.EntityReferenceFilter;
    CreatedOn: Date;
    CreatedOnBehalfBy: XQR.EntityReferenceFilter;
    CreditLimit: XQR.ValueContainerFilter<number>;
    CreditLimit_Base: XQR.ValueContainerFilter<number>;
    CreditOnHold: boolean;
    CustomerSizeCode: XQR.ValueContainerFilter<account_customersizecode>;
    CustomerTypeCode: XQR.ValueContainerFilter<account_customertypecode>;
    Description: string;
    DoNotBulkEMail: boolean;
    DoNotBulkPostalMail: boolean;
    DoNotEMail: boolean;
    DoNotFax: boolean;
    DoNotPhone: boolean;
    DoNotPostalMail: boolean;
    DoNotSendMM: boolean;
    EMailAddress1: string;
    EMailAddress2: string;
    EMailAddress3: string;
    EntityImageId: XQR.Guid;
    ExchangeRate: any;
    Fax: string;
    FollowEmail: boolean;
    FtpSiteURL: string;
    ImportSequenceNumber: number;
    IndustryCode: XQR.ValueContainerFilter<account_industrycode>;
    IsPrivate: boolean;
    LastOnHoldTime: Date;
    LastUsedInCampaign: Date;
    MarketCap: XQR.ValueContainerFilter<number>;
    MarketCap_Base: XQR.ValueContainerFilter<number>;
    MarketingOnly: boolean;
    MasterId: XQR.EntityReferenceFilter;
    Merged: boolean;
    ModifiedBy: XQR.EntityReferenceFilter;
    ModifiedByExternalParty: XQR.EntityReferenceFilter;
    ModifiedOn: Date;
    ModifiedOnBehalfBy: XQR.EntityReferenceFilter;
    Name: string;
    NumberOfEmployees: number;
    OnHoldTime: number;
    OverriddenCreatedOn: Date;
    OwnerId: XQR.EntityReferenceFilter;
    OwnershipCode: XQR.ValueContainerFilter<account_ownershipcode>;
    OwningBusinessUnit: XQR.EntityReferenceFilter;
    OwningTeam: XQR.EntityReferenceFilter;
    OwningUser: XQR.EntityReferenceFilter;
    ParentAccountId: XQR.EntityReferenceFilter;
    ParticipatesInWorkflow: boolean;
    PaymentTermsCode: XQR.ValueContainerFilter<account_paymenttermscode>;
    PreferredAppointmentDayCode: XQR.ValueContainerFilter<account_preferredappointmentdaycode>;
    PreferredAppointmentTimeCode: XQR.ValueContainerFilter<account_preferredappointmenttimecode>;
    PreferredContactMethodCode: XQR.ValueContainerFilter<account_preferredcontactmethodcode>;
    PreferredSystemUserId: XQR.EntityReferenceFilter;
    PrimaryContactId: XQR.EntityReferenceFilter;
    PrimarySatoriId: string;
    PrimaryTwitterId: string;
    ProcessId: XQR.Guid;
    Revenue: XQR.ValueContainerFilter<number>;
    Revenue_Base: XQR.ValueContainerFilter<number>;
    SIC: string;
    SLAId: XQR.EntityReferenceFilter;
    SLAInvokedId: XQR.EntityReferenceFilter;
    SharesOutstanding: number;
    ShippingMethodCode: XQR.ValueContainerFilter<account_shippingmethodcode>;
    StageId: XQR.Guid;
    StateCode: XQR.ValueContainerFilter<account_statecode>;
    StatusCode: XQR.ValueContainerFilter<account_statuscode>;
    StockExchange: string;
    Telephone1: string;
    Telephone2: string;
    Telephone3: string;
    TerritoryCode: XQR.ValueContainerFilter<account_territorycode>;
    TickerSymbol: string;
    TimeSpentByMeOnEmailAndMeetings: string;
    TimeZoneRuleVersionNumber: number;
    TransactionCurrencyId: XQR.EntityReferenceFilter;
    TraversedPath: string;
    UTCConversionTimeZoneCode: number;
    VersionNumber: number;
    WebSiteURL: string;
    msa_managingpartnerid: XQR.EntityReferenceFilter;
  }
  interface Account_Expand {
    Account_ActivityPointers: RestExpand<Account_Select, ActivityPointer_Select>;
    Account_Email_EmailSender: RestExpand<Account_Select, Email_Select>;
    Account_Email_SendersAccount: RestExpand<Account_Select, Email_Select>;
    Account_Emails: RestExpand<Account_Select, Email_Select>;
    Referencedaccount_master_account: RestExpand<Account_Select, Account_Select>;
    Referencedaccount_parent_account: RestExpand<Account_Select, Account_Select>;
    Referencedmsa_account_managingpartner: RestExpand<Account_Select, Account_Select>;
    Referencingaccount_master_account: RestExpand<Account_Select, Account_Select>;
    Referencingaccount_parent_account: RestExpand<Account_Select, Account_Select>;
    Referencingmsa_account_managingpartner: RestExpand<Account_Select, Account_Select>;
    account_activity_parties: RestExpand<Account_Select, ActivityParty_Select>;
    account_connections1: RestExpand<Account_Select, Connection_Select>;
    account_connections2: RestExpand<Account_Select, Connection_Select>;
    account_primary_contact: RestExpand<Account_Select, Contact_Select>;
    contact_customer_accounts: RestExpand<Account_Select, Contact_Select>;
    lk_accountbase_createdby: RestExpand<Account_Select, SystemUser_Select>;
    lk_accountbase_createdonbehalfby: RestExpand<Account_Select, SystemUser_Select>;
    lk_accountbase_modifiedby: RestExpand<Account_Select, SystemUser_Select>;
    lk_accountbase_modifiedonbehalfby: RestExpand<Account_Select, SystemUser_Select>;
    msa_contact_managingpartner: RestExpand<Account_Select, Contact_Select>;
    owner_accounts: RestExpand<Account_Select, SystemUser_Select>;
    system_user_accounts: RestExpand<Account_Select, SystemUser_Select>;
    user_accounts: RestExpand<Account_Select, SystemUser_Select>;
  }
}
interface RestEntities {
  Account: RestMapping<Rest.Account,Rest.Account_Select,Rest.Account_Expand,Rest.Account_Filter,Rest.AccountResult>;
}
