declare namespace Rest {
  interface ContactBase extends RestEntity {
    AccountId?: SDK.EntityReference | null;
    AccountRoleCode?: SDK.OptionSet<contact_accountrolecode> | null;
    Address1_AddressId?: string | null;
    Address1_AddressTypeCode?: SDK.OptionSet<contact_address1_addresstypecode> | null;
    Address1_City?: string | null;
    Address1_Composite?: string | null;
    Address1_Country?: string | null;
    Address1_County?: string | null;
    Address1_Fax?: string | null;
    Address1_FreightTermsCode?: SDK.OptionSet<contact_address1_freighttermscode> | null;
    Address1_Latitude?: number | null;
    Address1_Line1?: string | null;
    Address1_Line2?: string | null;
    Address1_Line3?: string | null;
    Address1_Longitude?: number | null;
    Address1_Name?: string | null;
    Address1_PostOfficeBox?: string | null;
    Address1_PostalCode?: string | null;
    Address1_PrimaryContactName?: string | null;
    Address1_ShippingMethodCode?: SDK.OptionSet<contact_address1_shippingmethodcode> | null;
    Address1_StateOrProvince?: string | null;
    Address1_Telephone1?: string | null;
    Address1_Telephone2?: string | null;
    Address1_Telephone3?: string | null;
    Address1_UPSZone?: string | null;
    Address1_UTCOffset?: number | null;
    Address2_AddressId?: string | null;
    Address2_AddressTypeCode?: SDK.OptionSet<contact_address2_addresstypecode> | null;
    Address2_City?: string | null;
    Address2_Composite?: string | null;
    Address2_Country?: string | null;
    Address2_County?: string | null;
    Address2_Fax?: string | null;
    Address2_FreightTermsCode?: SDK.OptionSet<contact_address2_freighttermscode> | null;
    Address2_Latitude?: number | null;
    Address2_Line1?: string | null;
    Address2_Line2?: string | null;
    Address2_Line3?: string | null;
    Address2_Longitude?: number | null;
    Address2_Name?: string | null;
    Address2_PostOfficeBox?: string | null;
    Address2_PostalCode?: string | null;
    Address2_PrimaryContactName?: string | null;
    Address2_ShippingMethodCode?: SDK.OptionSet<contact_address2_shippingmethodcode> | null;
    Address2_StateOrProvince?: string | null;
    Address2_Telephone1?: string | null;
    Address2_Telephone2?: string | null;
    Address2_Telephone3?: string | null;
    Address2_UPSZone?: string | null;
    Address2_UTCOffset?: number | null;
    Address3_AddressId?: string | null;
    Address3_AddressTypeCode?: SDK.OptionSet<contact_address3_addresstypecode> | null;
    Address3_City?: string | null;
    Address3_Composite?: string | null;
    Address3_Country?: string | null;
    Address3_County?: string | null;
    Address3_Fax?: string | null;
    Address3_FreightTermsCode?: SDK.OptionSet<contact_address3_freighttermscode> | null;
    Address3_Latitude?: number | null;
    Address3_Line1?: string | null;
    Address3_Line2?: string | null;
    Address3_Line3?: string | null;
    Address3_Longitude?: number | null;
    Address3_Name?: string | null;
    Address3_PostOfficeBox?: string | null;
    Address3_PostalCode?: string | null;
    Address3_PrimaryContactName?: string | null;
    Address3_ShippingMethodCode?: SDK.OptionSet<contact_address3_shippingmethodcode> | null;
    Address3_StateOrProvince?: string | null;
    Address3_Telephone1?: string | null;
    Address3_Telephone2?: string | null;
    Address3_Telephone3?: string | null;
    Address3_UPSZone?: string | null;
    Address3_UTCOffset?: number | null;
    Adx_CreatedByIPAddress?: string | null;
    Adx_CreatedByUsername?: string | null;
    Adx_ModifiedByIPAddress?: string | null;
    Adx_ModifiedByUsername?: string | null;
    Adx_OrganizationName?: string | null;
    Adx_ProfileIsAnonymous?: boolean | null;
    Adx_ProfileLastActivity?: Date | null;
    Adx_TimeZone?: number | null;
    Aging30?: SDK.Money | null;
    Aging30_Base?: SDK.Money | null;
    Aging60?: SDK.Money | null;
    Aging60_Base?: SDK.Money | null;
    Aging90?: SDK.Money | null;
    Aging90_Base?: SDK.Money | null;
    Anniversary?: Date | null;
    AnnualIncome?: SDK.Money | null;
    AnnualIncome_Base?: SDK.Money | null;
    AssistantName?: string | null;
    AssistantPhone?: string | null;
    BirthDate?: Date | null;
    Business2?: string | null;
    Callback?: string | null;
    ChildrensNames?: string | null;
    Company?: string | null;
    ContactId?: string | null;
    CreatedBy?: SDK.EntityReference | null;
    CreatedByExternalParty?: SDK.EntityReference | null;
    CreatedOn?: Date | null;
    CreatedOnBehalfBy?: SDK.EntityReference | null;
    CreditLimit?: SDK.Money | null;
    CreditLimit_Base?: SDK.Money | null;
    CreditOnHold?: boolean | null;
    CustomerSizeCode?: SDK.OptionSet<contact_customersizecode> | null;
    CustomerTypeCode?: SDK.OptionSet<contact_customertypecode> | null;
    Department?: string | null;
    Description?: string | null;
    DoNotBulkEMail?: boolean | null;
    DoNotBulkPostalMail?: boolean | null;
    DoNotEMail?: boolean | null;
    DoNotFax?: boolean | null;
    DoNotPhone?: boolean | null;
    DoNotPostalMail?: boolean | null;
    DoNotSendMM?: boolean | null;
    EMailAddress1?: string | null;
    EMailAddress2?: string | null;
    EMailAddress3?: string | null;
    EducationCode?: SDK.OptionSet<contact_educationcode> | null;
    EmployeeId?: string | null;
    EntityImageId?: string | null;
    ExchangeRate?: string | null;
    ExternalUserIdentifier?: string | null;
    FamilyStatusCode?: SDK.OptionSet<contact_familystatuscode> | null;
    Fax?: string | null;
    FirstName?: string | null;
    FollowEmail?: boolean | null;
    FtpSiteUrl?: string | null;
    FullName?: string | null;
    GenderCode?: SDK.OptionSet<contact_gendercode> | null;
    GovernmentId?: string | null;
    HasChildrenCode?: SDK.OptionSet<contact_haschildrencode> | null;
    Home2?: string | null;
    ImportSequenceNumber?: number | null;
    IsAutoCreate?: boolean | null;
    IsBackofficeCustomer?: boolean | null;
    IsPrivate?: boolean | null;
    JobTitle?: string | null;
    LastName?: string | null;
    LastOnHoldTime?: Date | null;
    LastUsedInCampaign?: Date | null;
    LeadSourceCode?: SDK.OptionSet<contact_leadsourcecode> | null;
    ManagerName?: string | null;
    ManagerPhone?: string | null;
    MarketingOnly?: boolean | null;
    MasterId?: SDK.EntityReference | null;
    Merged?: boolean | null;
    MiddleName?: string | null;
    MobilePhone?: string | null;
    ModifiedBy?: SDK.EntityReference | null;
    ModifiedByExternalParty?: SDK.EntityReference | null;
    ModifiedOn?: Date | null;
    ModifiedOnBehalfBy?: SDK.EntityReference | null;
    NickName?: string | null;
    NumberOfChildren?: number | null;
    OnHoldTime?: number | null;
    OverriddenCreatedOn?: Date | null;
    OwnerId?: SDK.EntityReference | null;
    OwningBusinessUnit?: SDK.EntityReference | null;
    OwningTeam?: SDK.EntityReference | null;
    OwningUser?: SDK.EntityReference | null;
    Pager?: string | null;
    ParentContactId?: SDK.EntityReference | null;
    ParentCustomerId?: SDK.EntityReference | null;
    ParticipatesInWorkflow?: boolean | null;
    PaymentTermsCode?: SDK.OptionSet<contact_paymenttermscode> | null;
    PreferredAppointmentDayCode?: SDK.OptionSet<contact_preferredappointmentdaycode> | null;
    PreferredAppointmentTimeCode?: SDK.OptionSet<contact_preferredappointmenttimecode> | null;
    PreferredContactMethodCode?: SDK.OptionSet<contact_preferredcontactmethodcode> | null;
    PreferredSystemUserId?: SDK.EntityReference | null;
    ProcessId?: string | null;
    SLAId?: SDK.EntityReference | null;
    SLAInvokedId?: SDK.EntityReference | null;
    Salutation?: string | null;
    ShippingMethodCode?: SDK.OptionSet<contact_shippingmethodcode> | null;
    SpousesName?: string | null;
    StageId?: string | null;
    StateCode?: SDK.OptionSet<contact_statecode> | null;
    StatusCode?: SDK.OptionSet<contact_statuscode> | null;
    SubscriptionId?: string | null;
    Suffix?: string | null;
    Telephone1?: string | null;
    Telephone2?: string | null;
    Telephone3?: string | null;
    TerritoryCode?: SDK.OptionSet<contact_territorycode> | null;
    TimeSpentByMeOnEmailAndMeetings?: string | null;
    TimeZoneRuleVersionNumber?: number | null;
    TransactionCurrencyId?: SDK.EntityReference | null;
    TraversedPath?: string | null;
    UTCConversionTimeZoneCode?: number | null;
    VersionNumber?: number | null;
    WebSiteUrl?: string | null;
    adx_ConfirmRemovePassword?: boolean | null;
    adx_PublicProfileCopy?: string | null;
    adx_identity_accessfailedcount?: number | null;
    adx_identity_emailaddress1confirmed?: boolean | null;
    adx_identity_lastsuccessfullogin?: Date | null;
    adx_identity_locallogindisabled?: boolean | null;
    adx_identity_lockoutenabled?: boolean | null;
    adx_identity_lockoutenddate?: Date | null;
    adx_identity_logonenabled?: boolean | null;
    adx_identity_mobilephoneconfirmed?: boolean | null;
    adx_identity_newpassword?: string | null;
    adx_identity_passwordhash?: string | null;
    adx_identity_securitystamp?: string | null;
    adx_identity_twofactorenabled?: boolean | null;
    adx_identity_username?: string | null;
    adx_preferredlanguageid?: SDK.EntityReference | null;
    adx_profilealert?: boolean | null;
    adx_profilealertdate?: Date | null;
    adx_profilealertinstructions?: string | null;
    adx_profilemodifiedon?: Date | null;
    msa_managingpartnerid?: SDK.EntityReference | null;
    msdyn_disablewebtracking?: boolean | null;
    msdyn_isminor?: boolean | null;
    msdyn_isminorwithparentalconsent?: boolean | null;
    msdyn_portaltermsagreementdate?: Date | null;
  }
  interface Contact extends ContactBase {
    Referencedcontact_customer_contacts?: Contact[] | null;
    Referencedcontact_master_contact?: Contact[] | null;
    Referencingcontact_customer_contacts?: Contact | null;
    Referencingcontact_master_contact?: Contact | null;
    account_primary_contact?: Account[] | null;
    contact_activity_parties?: ActivityParty[] | null;
    contact_connections1?: Connection[] | null;
    contact_connections2?: Connection[] | null;
    contact_customer_accounts?: Account | null;
    msa_contact_managingpartner?: Account | null;
  }
  interface ContactResult extends ContactBase {
    Referencedcontact_customer_contacts?: SDK.Results<ContactResult> | null;
    Referencedcontact_master_contact?: SDK.Results<ContactResult> | null;
    Referencingcontact_customer_contacts?: Contact | null;
    Referencingcontact_master_contact?: Contact | null;
    account_primary_contact?: SDK.Results<AccountResult> | null;
    contact_activity_parties?: SDK.Results<ActivityPartyResult> | null;
    contact_connections1?: SDK.Results<ConnectionResult> | null;
    contact_connections2?: SDK.Results<ConnectionResult> | null;
    contact_customer_accounts?: Account | null;
    msa_contact_managingpartner?: Account | null;
  }
  interface Contact_Select extends Contact_Expand {
    AccountId: RestAttribute<Contact_Select>;
    AccountRoleCode: RestAttribute<Contact_Select>;
    Address1_AddressId: RestAttribute<Contact_Select>;
    Address1_AddressTypeCode: RestAttribute<Contact_Select>;
    Address1_City: RestAttribute<Contact_Select>;
    Address1_Composite: RestAttribute<Contact_Select>;
    Address1_Country: RestAttribute<Contact_Select>;
    Address1_County: RestAttribute<Contact_Select>;
    Address1_Fax: RestAttribute<Contact_Select>;
    Address1_FreightTermsCode: RestAttribute<Contact_Select>;
    Address1_Latitude: RestAttribute<Contact_Select>;
    Address1_Line1: RestAttribute<Contact_Select>;
    Address1_Line2: RestAttribute<Contact_Select>;
    Address1_Line3: RestAttribute<Contact_Select>;
    Address1_Longitude: RestAttribute<Contact_Select>;
    Address1_Name: RestAttribute<Contact_Select>;
    Address1_PostOfficeBox: RestAttribute<Contact_Select>;
    Address1_PostalCode: RestAttribute<Contact_Select>;
    Address1_PrimaryContactName: RestAttribute<Contact_Select>;
    Address1_ShippingMethodCode: RestAttribute<Contact_Select>;
    Address1_StateOrProvince: RestAttribute<Contact_Select>;
    Address1_Telephone1: RestAttribute<Contact_Select>;
    Address1_Telephone2: RestAttribute<Contact_Select>;
    Address1_Telephone3: RestAttribute<Contact_Select>;
    Address1_UPSZone: RestAttribute<Contact_Select>;
    Address1_UTCOffset: RestAttribute<Contact_Select>;
    Address2_AddressId: RestAttribute<Contact_Select>;
    Address2_AddressTypeCode: RestAttribute<Contact_Select>;
    Address2_City: RestAttribute<Contact_Select>;
    Address2_Composite: RestAttribute<Contact_Select>;
    Address2_Country: RestAttribute<Contact_Select>;
    Address2_County: RestAttribute<Contact_Select>;
    Address2_Fax: RestAttribute<Contact_Select>;
    Address2_FreightTermsCode: RestAttribute<Contact_Select>;
    Address2_Latitude: RestAttribute<Contact_Select>;
    Address2_Line1: RestAttribute<Contact_Select>;
    Address2_Line2: RestAttribute<Contact_Select>;
    Address2_Line3: RestAttribute<Contact_Select>;
    Address2_Longitude: RestAttribute<Contact_Select>;
    Address2_Name: RestAttribute<Contact_Select>;
    Address2_PostOfficeBox: RestAttribute<Contact_Select>;
    Address2_PostalCode: RestAttribute<Contact_Select>;
    Address2_PrimaryContactName: RestAttribute<Contact_Select>;
    Address2_ShippingMethodCode: RestAttribute<Contact_Select>;
    Address2_StateOrProvince: RestAttribute<Contact_Select>;
    Address2_Telephone1: RestAttribute<Contact_Select>;
    Address2_Telephone2: RestAttribute<Contact_Select>;
    Address2_Telephone3: RestAttribute<Contact_Select>;
    Address2_UPSZone: RestAttribute<Contact_Select>;
    Address2_UTCOffset: RestAttribute<Contact_Select>;
    Address3_AddressId: RestAttribute<Contact_Select>;
    Address3_AddressTypeCode: RestAttribute<Contact_Select>;
    Address3_City: RestAttribute<Contact_Select>;
    Address3_Composite: RestAttribute<Contact_Select>;
    Address3_Country: RestAttribute<Contact_Select>;
    Address3_County: RestAttribute<Contact_Select>;
    Address3_Fax: RestAttribute<Contact_Select>;
    Address3_FreightTermsCode: RestAttribute<Contact_Select>;
    Address3_Latitude: RestAttribute<Contact_Select>;
    Address3_Line1: RestAttribute<Contact_Select>;
    Address3_Line2: RestAttribute<Contact_Select>;
    Address3_Line3: RestAttribute<Contact_Select>;
    Address3_Longitude: RestAttribute<Contact_Select>;
    Address3_Name: RestAttribute<Contact_Select>;
    Address3_PostOfficeBox: RestAttribute<Contact_Select>;
    Address3_PostalCode: RestAttribute<Contact_Select>;
    Address3_PrimaryContactName: RestAttribute<Contact_Select>;
    Address3_ShippingMethodCode: RestAttribute<Contact_Select>;
    Address3_StateOrProvince: RestAttribute<Contact_Select>;
    Address3_Telephone1: RestAttribute<Contact_Select>;
    Address3_Telephone2: RestAttribute<Contact_Select>;
    Address3_Telephone3: RestAttribute<Contact_Select>;
    Address3_UPSZone: RestAttribute<Contact_Select>;
    Address3_UTCOffset: RestAttribute<Contact_Select>;
    Adx_CreatedByIPAddress: RestAttribute<Contact_Select>;
    Adx_CreatedByUsername: RestAttribute<Contact_Select>;
    Adx_ModifiedByIPAddress: RestAttribute<Contact_Select>;
    Adx_ModifiedByUsername: RestAttribute<Contact_Select>;
    Adx_OrganizationName: RestAttribute<Contact_Select>;
    Adx_ProfileIsAnonymous: RestAttribute<Contact_Select>;
    Adx_ProfileLastActivity: RestAttribute<Contact_Select>;
    Adx_TimeZone: RestAttribute<Contact_Select>;
    Aging30: RestAttribute<Contact_Select>;
    Aging30_Base: RestAttribute<Contact_Select>;
    Aging60: RestAttribute<Contact_Select>;
    Aging60_Base: RestAttribute<Contact_Select>;
    Aging90: RestAttribute<Contact_Select>;
    Aging90_Base: RestAttribute<Contact_Select>;
    Anniversary: RestAttribute<Contact_Select>;
    AnnualIncome: RestAttribute<Contact_Select>;
    AnnualIncome_Base: RestAttribute<Contact_Select>;
    AssistantName: RestAttribute<Contact_Select>;
    AssistantPhone: RestAttribute<Contact_Select>;
    BirthDate: RestAttribute<Contact_Select>;
    Business2: RestAttribute<Contact_Select>;
    Callback: RestAttribute<Contact_Select>;
    ChildrensNames: RestAttribute<Contact_Select>;
    Company: RestAttribute<Contact_Select>;
    ContactId: RestAttribute<Contact_Select>;
    CreatedBy: RestAttribute<Contact_Select>;
    CreatedByExternalParty: RestAttribute<Contact_Select>;
    CreatedOn: RestAttribute<Contact_Select>;
    CreatedOnBehalfBy: RestAttribute<Contact_Select>;
    CreditLimit: RestAttribute<Contact_Select>;
    CreditLimit_Base: RestAttribute<Contact_Select>;
    CreditOnHold: RestAttribute<Contact_Select>;
    CustomerSizeCode: RestAttribute<Contact_Select>;
    CustomerTypeCode: RestAttribute<Contact_Select>;
    Department: RestAttribute<Contact_Select>;
    Description: RestAttribute<Contact_Select>;
    DoNotBulkEMail: RestAttribute<Contact_Select>;
    DoNotBulkPostalMail: RestAttribute<Contact_Select>;
    DoNotEMail: RestAttribute<Contact_Select>;
    DoNotFax: RestAttribute<Contact_Select>;
    DoNotPhone: RestAttribute<Contact_Select>;
    DoNotPostalMail: RestAttribute<Contact_Select>;
    DoNotSendMM: RestAttribute<Contact_Select>;
    EMailAddress1: RestAttribute<Contact_Select>;
    EMailAddress2: RestAttribute<Contact_Select>;
    EMailAddress3: RestAttribute<Contact_Select>;
    EducationCode: RestAttribute<Contact_Select>;
    EmployeeId: RestAttribute<Contact_Select>;
    EntityImageId: RestAttribute<Contact_Select>;
    ExchangeRate: RestAttribute<Contact_Select>;
    ExternalUserIdentifier: RestAttribute<Contact_Select>;
    FamilyStatusCode: RestAttribute<Contact_Select>;
    Fax: RestAttribute<Contact_Select>;
    FirstName: RestAttribute<Contact_Select>;
    FollowEmail: RestAttribute<Contact_Select>;
    FtpSiteUrl: RestAttribute<Contact_Select>;
    FullName: RestAttribute<Contact_Select>;
    GenderCode: RestAttribute<Contact_Select>;
    GovernmentId: RestAttribute<Contact_Select>;
    HasChildrenCode: RestAttribute<Contact_Select>;
    Home2: RestAttribute<Contact_Select>;
    ImportSequenceNumber: RestAttribute<Contact_Select>;
    IsAutoCreate: RestAttribute<Contact_Select>;
    IsBackofficeCustomer: RestAttribute<Contact_Select>;
    IsPrivate: RestAttribute<Contact_Select>;
    JobTitle: RestAttribute<Contact_Select>;
    LastName: RestAttribute<Contact_Select>;
    LastOnHoldTime: RestAttribute<Contact_Select>;
    LastUsedInCampaign: RestAttribute<Contact_Select>;
    LeadSourceCode: RestAttribute<Contact_Select>;
    ManagerName: RestAttribute<Contact_Select>;
    ManagerPhone: RestAttribute<Contact_Select>;
    MarketingOnly: RestAttribute<Contact_Select>;
    MasterId: RestAttribute<Contact_Select>;
    Merged: RestAttribute<Contact_Select>;
    MiddleName: RestAttribute<Contact_Select>;
    MobilePhone: RestAttribute<Contact_Select>;
    ModifiedBy: RestAttribute<Contact_Select>;
    ModifiedByExternalParty: RestAttribute<Contact_Select>;
    ModifiedOn: RestAttribute<Contact_Select>;
    ModifiedOnBehalfBy: RestAttribute<Contact_Select>;
    NickName: RestAttribute<Contact_Select>;
    NumberOfChildren: RestAttribute<Contact_Select>;
    OnHoldTime: RestAttribute<Contact_Select>;
    OverriddenCreatedOn: RestAttribute<Contact_Select>;
    OwnerId: RestAttribute<Contact_Select>;
    OwningBusinessUnit: RestAttribute<Contact_Select>;
    OwningTeam: RestAttribute<Contact_Select>;
    OwningUser: RestAttribute<Contact_Select>;
    Pager: RestAttribute<Contact_Select>;
    ParentContactId: RestAttribute<Contact_Select>;
    ParentCustomerId: RestAttribute<Contact_Select>;
    ParticipatesInWorkflow: RestAttribute<Contact_Select>;
    PaymentTermsCode: RestAttribute<Contact_Select>;
    PreferredAppointmentDayCode: RestAttribute<Contact_Select>;
    PreferredAppointmentTimeCode: RestAttribute<Contact_Select>;
    PreferredContactMethodCode: RestAttribute<Contact_Select>;
    PreferredSystemUserId: RestAttribute<Contact_Select>;
    ProcessId: RestAttribute<Contact_Select>;
    SLAId: RestAttribute<Contact_Select>;
    SLAInvokedId: RestAttribute<Contact_Select>;
    Salutation: RestAttribute<Contact_Select>;
    ShippingMethodCode: RestAttribute<Contact_Select>;
    SpousesName: RestAttribute<Contact_Select>;
    StageId: RestAttribute<Contact_Select>;
    StateCode: RestAttribute<Contact_Select>;
    StatusCode: RestAttribute<Contact_Select>;
    SubscriptionId: RestAttribute<Contact_Select>;
    Suffix: RestAttribute<Contact_Select>;
    Telephone1: RestAttribute<Contact_Select>;
    Telephone2: RestAttribute<Contact_Select>;
    Telephone3: RestAttribute<Contact_Select>;
    TerritoryCode: RestAttribute<Contact_Select>;
    TimeSpentByMeOnEmailAndMeetings: RestAttribute<Contact_Select>;
    TimeZoneRuleVersionNumber: RestAttribute<Contact_Select>;
    TransactionCurrencyId: RestAttribute<Contact_Select>;
    TraversedPath: RestAttribute<Contact_Select>;
    UTCConversionTimeZoneCode: RestAttribute<Contact_Select>;
    VersionNumber: RestAttribute<Contact_Select>;
    WebSiteUrl: RestAttribute<Contact_Select>;
    adx_ConfirmRemovePassword: RestAttribute<Contact_Select>;
    adx_PublicProfileCopy: RestAttribute<Contact_Select>;
    adx_identity_accessfailedcount: RestAttribute<Contact_Select>;
    adx_identity_emailaddress1confirmed: RestAttribute<Contact_Select>;
    adx_identity_lastsuccessfullogin: RestAttribute<Contact_Select>;
    adx_identity_locallogindisabled: RestAttribute<Contact_Select>;
    adx_identity_lockoutenabled: RestAttribute<Contact_Select>;
    adx_identity_lockoutenddate: RestAttribute<Contact_Select>;
    adx_identity_logonenabled: RestAttribute<Contact_Select>;
    adx_identity_mobilephoneconfirmed: RestAttribute<Contact_Select>;
    adx_identity_newpassword: RestAttribute<Contact_Select>;
    adx_identity_passwordhash: RestAttribute<Contact_Select>;
    adx_identity_securitystamp: RestAttribute<Contact_Select>;
    adx_identity_twofactorenabled: RestAttribute<Contact_Select>;
    adx_identity_username: RestAttribute<Contact_Select>;
    adx_preferredlanguageid: RestAttribute<Contact_Select>;
    adx_profilealert: RestAttribute<Contact_Select>;
    adx_profilealertdate: RestAttribute<Contact_Select>;
    adx_profilealertinstructions: RestAttribute<Contact_Select>;
    adx_profilemodifiedon: RestAttribute<Contact_Select>;
    msa_managingpartnerid: RestAttribute<Contact_Select>;
    msdyn_disablewebtracking: RestAttribute<Contact_Select>;
    msdyn_isminor: RestAttribute<Contact_Select>;
    msdyn_isminorwithparentalconsent: RestAttribute<Contact_Select>;
    msdyn_portaltermsagreementdate: RestAttribute<Contact_Select>;
  }
  interface Contact_Filter {
    AccountId: XQR.EntityReferenceFilter;
    AccountRoleCode: XQR.ValueContainerFilter<contact_accountrolecode>;
    Address1_AddressId: XQR.Guid;
    Address1_AddressTypeCode: XQR.ValueContainerFilter<contact_address1_addresstypecode>;
    Address1_City: string;
    Address1_Composite: string;
    Address1_Country: string;
    Address1_County: string;
    Address1_Fax: string;
    Address1_FreightTermsCode: XQR.ValueContainerFilter<contact_address1_freighttermscode>;
    Address1_Latitude: number;
    Address1_Line1: string;
    Address1_Line2: string;
    Address1_Line3: string;
    Address1_Longitude: number;
    Address1_Name: string;
    Address1_PostOfficeBox: string;
    Address1_PostalCode: string;
    Address1_PrimaryContactName: string;
    Address1_ShippingMethodCode: XQR.ValueContainerFilter<contact_address1_shippingmethodcode>;
    Address1_StateOrProvince: string;
    Address1_Telephone1: string;
    Address1_Telephone2: string;
    Address1_Telephone3: string;
    Address1_UPSZone: string;
    Address1_UTCOffset: number;
    Address2_AddressId: XQR.Guid;
    Address2_AddressTypeCode: XQR.ValueContainerFilter<contact_address2_addresstypecode>;
    Address2_City: string;
    Address2_Composite: string;
    Address2_Country: string;
    Address2_County: string;
    Address2_Fax: string;
    Address2_FreightTermsCode: XQR.ValueContainerFilter<contact_address2_freighttermscode>;
    Address2_Latitude: number;
    Address2_Line1: string;
    Address2_Line2: string;
    Address2_Line3: string;
    Address2_Longitude: number;
    Address2_Name: string;
    Address2_PostOfficeBox: string;
    Address2_PostalCode: string;
    Address2_PrimaryContactName: string;
    Address2_ShippingMethodCode: XQR.ValueContainerFilter<contact_address2_shippingmethodcode>;
    Address2_StateOrProvince: string;
    Address2_Telephone1: string;
    Address2_Telephone2: string;
    Address2_Telephone3: string;
    Address2_UPSZone: string;
    Address2_UTCOffset: number;
    Address3_AddressId: XQR.Guid;
    Address3_AddressTypeCode: XQR.ValueContainerFilter<contact_address3_addresstypecode>;
    Address3_City: string;
    Address3_Composite: string;
    Address3_Country: string;
    Address3_County: string;
    Address3_Fax: string;
    Address3_FreightTermsCode: XQR.ValueContainerFilter<contact_address3_freighttermscode>;
    Address3_Latitude: number;
    Address3_Line1: string;
    Address3_Line2: string;
    Address3_Line3: string;
    Address3_Longitude: number;
    Address3_Name: string;
    Address3_PostOfficeBox: string;
    Address3_PostalCode: string;
    Address3_PrimaryContactName: string;
    Address3_ShippingMethodCode: XQR.ValueContainerFilter<contact_address3_shippingmethodcode>;
    Address3_StateOrProvince: string;
    Address3_Telephone1: string;
    Address3_Telephone2: string;
    Address3_Telephone3: string;
    Address3_UPSZone: string;
    Address3_UTCOffset: number;
    Adx_CreatedByIPAddress: string;
    Adx_CreatedByUsername: string;
    Adx_ModifiedByIPAddress: string;
    Adx_ModifiedByUsername: string;
    Adx_OrganizationName: string;
    Adx_ProfileIsAnonymous: boolean;
    Adx_ProfileLastActivity: Date;
    Adx_TimeZone: number;
    Aging30: XQR.ValueContainerFilter<number>;
    Aging30_Base: XQR.ValueContainerFilter<number>;
    Aging60: XQR.ValueContainerFilter<number>;
    Aging60_Base: XQR.ValueContainerFilter<number>;
    Aging90: XQR.ValueContainerFilter<number>;
    Aging90_Base: XQR.ValueContainerFilter<number>;
    Anniversary: Date;
    AnnualIncome: XQR.ValueContainerFilter<number>;
    AnnualIncome_Base: XQR.ValueContainerFilter<number>;
    AssistantName: string;
    AssistantPhone: string;
    BirthDate: Date;
    Business2: string;
    Callback: string;
    ChildrensNames: string;
    Company: string;
    ContactId: XQR.Guid;
    CreatedBy: XQR.EntityReferenceFilter;
    CreatedByExternalParty: XQR.EntityReferenceFilter;
    CreatedOn: Date;
    CreatedOnBehalfBy: XQR.EntityReferenceFilter;
    CreditLimit: XQR.ValueContainerFilter<number>;
    CreditLimit_Base: XQR.ValueContainerFilter<number>;
    CreditOnHold: boolean;
    CustomerSizeCode: XQR.ValueContainerFilter<contact_customersizecode>;
    CustomerTypeCode: XQR.ValueContainerFilter<contact_customertypecode>;
    Department: string;
    Description: string;
    DoNotBulkEMail: boolean;
    DoNotBulkPostalMail: boolean;
    DoNotEMail: boolean;
    DoNotFax: boolean;
    DoNotPhone: boolean;
    DoNotPostalMail: boolean;
    DoNotSendMM: boolean;
    EMailAddress1: string;
    EMailAddress2: string;
    EMailAddress3: string;
    EducationCode: XQR.ValueContainerFilter<contact_educationcode>;
    EmployeeId: string;
    EntityImageId: XQR.Guid;
    ExchangeRate: any;
    ExternalUserIdentifier: string;
    FamilyStatusCode: XQR.ValueContainerFilter<contact_familystatuscode>;
    Fax: string;
    FirstName: string;
    FollowEmail: boolean;
    FtpSiteUrl: string;
    FullName: string;
    GenderCode: XQR.ValueContainerFilter<contact_gendercode>;
    GovernmentId: string;
    HasChildrenCode: XQR.ValueContainerFilter<contact_haschildrencode>;
    Home2: string;
    ImportSequenceNumber: number;
    IsAutoCreate: boolean;
    IsBackofficeCustomer: boolean;
    IsPrivate: boolean;
    JobTitle: string;
    LastName: string;
    LastOnHoldTime: Date;
    LastUsedInCampaign: Date;
    LeadSourceCode: XQR.ValueContainerFilter<contact_leadsourcecode>;
    ManagerName: string;
    ManagerPhone: string;
    MarketingOnly: boolean;
    MasterId: XQR.EntityReferenceFilter;
    Merged: boolean;
    MiddleName: string;
    MobilePhone: string;
    ModifiedBy: XQR.EntityReferenceFilter;
    ModifiedByExternalParty: XQR.EntityReferenceFilter;
    ModifiedOn: Date;
    ModifiedOnBehalfBy: XQR.EntityReferenceFilter;
    NickName: string;
    NumberOfChildren: number;
    OnHoldTime: number;
    OverriddenCreatedOn: Date;
    OwnerId: XQR.EntityReferenceFilter;
    OwningBusinessUnit: XQR.EntityReferenceFilter;
    OwningTeam: XQR.EntityReferenceFilter;
    OwningUser: XQR.EntityReferenceFilter;
    Pager: string;
    ParentContactId: XQR.EntityReferenceFilter;
    ParentCustomerId: XQR.EntityReferenceFilter;
    ParticipatesInWorkflow: boolean;
    PaymentTermsCode: XQR.ValueContainerFilter<contact_paymenttermscode>;
    PreferredAppointmentDayCode: XQR.ValueContainerFilter<contact_preferredappointmentdaycode>;
    PreferredAppointmentTimeCode: XQR.ValueContainerFilter<contact_preferredappointmenttimecode>;
    PreferredContactMethodCode: XQR.ValueContainerFilter<contact_preferredcontactmethodcode>;
    PreferredSystemUserId: XQR.EntityReferenceFilter;
    ProcessId: XQR.Guid;
    SLAId: XQR.EntityReferenceFilter;
    SLAInvokedId: XQR.EntityReferenceFilter;
    Salutation: string;
    ShippingMethodCode: XQR.ValueContainerFilter<contact_shippingmethodcode>;
    SpousesName: string;
    StageId: XQR.Guid;
    StateCode: XQR.ValueContainerFilter<contact_statecode>;
    StatusCode: XQR.ValueContainerFilter<contact_statuscode>;
    SubscriptionId: XQR.Guid;
    Suffix: string;
    Telephone1: string;
    Telephone2: string;
    Telephone3: string;
    TerritoryCode: XQR.ValueContainerFilter<contact_territorycode>;
    TimeSpentByMeOnEmailAndMeetings: string;
    TimeZoneRuleVersionNumber: number;
    TransactionCurrencyId: XQR.EntityReferenceFilter;
    TraversedPath: string;
    UTCConversionTimeZoneCode: number;
    VersionNumber: number;
    WebSiteUrl: string;
    adx_ConfirmRemovePassword: boolean;
    adx_PublicProfileCopy: string;
    adx_identity_accessfailedcount: number;
    adx_identity_emailaddress1confirmed: boolean;
    adx_identity_lastsuccessfullogin: Date;
    adx_identity_locallogindisabled: boolean;
    adx_identity_lockoutenabled: boolean;
    adx_identity_lockoutenddate: Date;
    adx_identity_logonenabled: boolean;
    adx_identity_mobilephoneconfirmed: boolean;
    adx_identity_newpassword: string;
    adx_identity_passwordhash: string;
    adx_identity_securitystamp: string;
    adx_identity_twofactorenabled: boolean;
    adx_identity_username: string;
    adx_preferredlanguageid: XQR.EntityReferenceFilter;
    adx_profilealert: boolean;
    adx_profilealertdate: Date;
    adx_profilealertinstructions: string;
    adx_profilemodifiedon: Date;
    msa_managingpartnerid: XQR.EntityReferenceFilter;
    msdyn_disablewebtracking: boolean;
    msdyn_isminor: boolean;
    msdyn_isminorwithparentalconsent: boolean;
    msdyn_portaltermsagreementdate: Date;
  }
  interface Contact_Expand {
    Referencedcontact_customer_contacts: RestExpand<Contact_Select, Contact_Select>;
    Referencedcontact_master_contact: RestExpand<Contact_Select, Contact_Select>;
    Referencingcontact_customer_contacts: RestExpand<Contact_Select, Contact_Select>;
    Referencingcontact_master_contact: RestExpand<Contact_Select, Contact_Select>;
    account_primary_contact: RestExpand<Contact_Select, Account_Select>;
    contact_activity_parties: RestExpand<Contact_Select, ActivityParty_Select>;
    contact_connections1: RestExpand<Contact_Select, Connection_Select>;
    contact_connections2: RestExpand<Contact_Select, Connection_Select>;
    contact_customer_accounts: RestExpand<Contact_Select, Account_Select>;
    msa_contact_managingpartner: RestExpand<Contact_Select, Account_Select>;
  }
}
interface RestEntities {
  Contact: RestMapping<Rest.Contact,Rest.Contact_Select,Rest.Contact_Expand,Rest.Contact_Filter,Rest.ContactResult>;
}
