declare namespace Rest {
  interface EmailBase extends RestEntity {
    ActivityAdditionalParams?: string | null;
    ActivityId?: string | null;
    ActivityTypeCode?: string | null;
    ActualDurationMinutes?: number | null;
    ActualEnd?: Date | null;
    ActualStart?: Date | null;
    AttachmentCount?: number | null;
    AttachmentOpenCount?: number | null;
    BaseConversationIndexHash?: number | null;
    Category?: string | null;
    Compressed?: boolean | null;
    ConversationIndex?: string | null;
    ConversationTrackingId?: string | null;
    CorrelationMethod?: SDK.OptionSet<email_correlationmethod> | null;
    CreatedBy?: SDK.EntityReference | null;
    CreatedOn?: Date | null;
    CreatedOnBehalfBy?: SDK.EntityReference | null;
    DelayedEmailSendTime?: Date | null;
    DeliveryAttempts?: number | null;
    DeliveryPriorityCode?: SDK.OptionSet<activitypointer_deliveryprioritycode> | null;
    DeliveryReceiptRequested?: boolean | null;
    Description?: string | null;
    DirectionCode?: boolean | null;
    EmailReminderExpiryTime?: Date | null;
    EmailReminderStatus?: SDK.OptionSet<email_reminderstatus> | null;
    EmailReminderText?: string | null;
    EmailReminderType?: SDK.OptionSet<email_remindertype> | null;
    EmailSender?: SDK.EntityReference | null;
    EmailTrackingId?: string | null;
    ExchangeRate?: string | null;
    FollowEmailUserPreference?: boolean | null;
    ImportSequenceNumber?: number | null;
    InReplyTo?: string | null;
    IsBilled?: boolean | null;
    IsEmailFollowed?: boolean | null;
    IsEmailReminderSet?: boolean | null;
    IsRegularActivity?: boolean | null;
    IsUnsafe?: number | null;
    IsWorkflowCreated?: boolean | null;
    LastOnHoldTime?: Date | null;
    LastOpenedTime?: Date | null;
    LinksClickedCount?: number | null;
    MessageId?: string | null;
    MessageIdDupCheck?: string | null;
    MimeType?: string | null;
    ModifiedBy?: SDK.EntityReference | null;
    ModifiedOn?: Date | null;
    ModifiedOnBehalfBy?: SDK.EntityReference | null;
    Notifications?: SDK.OptionSet<email_notifications> | null;
    OnHoldTime?: number | null;
    OpenCount?: number | null;
    OverriddenCreatedOn?: Date | null;
    OwnerId?: SDK.EntityReference | null;
    OwningBusinessUnit?: SDK.EntityReference | null;
    OwningTeam?: SDK.EntityReference | null;
    OwningUser?: SDK.EntityReference | null;
    ParentActivityId?: SDK.EntityReference | null;
    PostponeEmailProcessingUntil?: Date | null;
    PriorityCode?: SDK.OptionSet<email_prioritycode> | null;
    ProcessId?: string | null;
    ReadReceiptRequested?: boolean | null;
    RegardingObjectId?: SDK.EntityReference | null;
    ReminderActionCardId?: string | null;
    ReplyCount?: number | null;
    SLAId?: SDK.EntityReference | null;
    SLAInvokedId?: SDK.EntityReference | null;
    ScheduledDurationMinutes?: number | null;
    ScheduledEnd?: Date | null;
    ScheduledStart?: Date | null;
    Sender?: string | null;
    SenderMailboxId?: SDK.EntityReference | null;
    SendersAccount?: SDK.EntityReference | null;
    SentOn?: Date | null;
    SortDate?: Date | null;
    StageId?: string | null;
    StateCode?: SDK.OptionSet<email_statecode> | null;
    StatusCode?: SDK.OptionSet<email_statuscode> | null;
    Subcategory?: string | null;
    Subject?: string | null;
    SubmittedBy?: string | null;
    TemplateId?: SDK.EntityReference | null;
    TimeZoneRuleVersionNumber?: number | null;
    ToRecipients?: string | null;
    TrackingToken?: string | null;
    TransactionCurrencyId?: SDK.EntityReference | null;
    TraversedPath?: string | null;
    UTCConversionTimeZoneCode?: number | null;
    VersionNumber?: number | null;
    bcc?: SDK.EntityReference | null;
    cc?: SDK.EntityReference | null;
    from?: SDK.EntityReference | null;
    to?: SDK.EntityReference | null;
  }
  interface Email extends EmailBase {
    Account_Email_EmailSender?: Account | null;
    Account_Email_SendersAccount?: Account | null;
    Account_Emails?: Account | null;
    Contact_Email_EmailSender?: Contact | null;
    Contact_Emails?: Contact | null;
    Referencedemail_email_parentactivityid?: Email[] | null;
    Referencingemail_email_parentactivityid?: Email | null;
    SystemUser_Email_EmailSender?: SystemUser | null;
    activity_pointer_email?: ActivityPointer | null;
    email_activity_parties?: ActivityParty[] | null;
    email_connections1?: Connection[] | null;
    email_connections2?: Connection[] | null;
    lk_email_createdby?: SystemUser | null;
    lk_email_createdonbehalfby?: SystemUser | null;
    lk_email_modifiedby?: SystemUser | null;
    lk_email_modifiedonbehalfby?: SystemUser | null;
    user_email?: SystemUser | null;
  }
  interface EmailResult extends EmailBase {
    Account_Email_EmailSender?: Account | null;
    Account_Email_SendersAccount?: Account | null;
    Account_Emails?: Account | null;
    Contact_Email_EmailSender?: Contact | null;
    Contact_Emails?: Contact | null;
    Referencedemail_email_parentactivityid?: SDK.Results<EmailResult> | null;
    Referencingemail_email_parentactivityid?: Email | null;
    SystemUser_Email_EmailSender?: SystemUser | null;
    activity_pointer_email?: ActivityPointer | null;
    email_activity_parties?: SDK.Results<ActivityPartyResult> | null;
    email_connections1?: SDK.Results<ConnectionResult> | null;
    email_connections2?: SDK.Results<ConnectionResult> | null;
    lk_email_createdby?: SystemUser | null;
    lk_email_createdonbehalfby?: SystemUser | null;
    lk_email_modifiedby?: SystemUser | null;
    lk_email_modifiedonbehalfby?: SystemUser | null;
    user_email?: SystemUser | null;
  }
  interface Email_Select extends Email_Expand {
    ActivityAdditionalParams: RestAttribute<Email_Select>;
    ActivityId: RestAttribute<Email_Select>;
    ActivityTypeCode: RestAttribute<Email_Select>;
    ActualDurationMinutes: RestAttribute<Email_Select>;
    ActualEnd: RestAttribute<Email_Select>;
    ActualStart: RestAttribute<Email_Select>;
    AttachmentCount: RestAttribute<Email_Select>;
    AttachmentOpenCount: RestAttribute<Email_Select>;
    BaseConversationIndexHash: RestAttribute<Email_Select>;
    Category: RestAttribute<Email_Select>;
    Compressed: RestAttribute<Email_Select>;
    ConversationIndex: RestAttribute<Email_Select>;
    ConversationTrackingId: RestAttribute<Email_Select>;
    CorrelationMethod: RestAttribute<Email_Select>;
    CreatedBy: RestAttribute<Email_Select>;
    CreatedOn: RestAttribute<Email_Select>;
    CreatedOnBehalfBy: RestAttribute<Email_Select>;
    DelayedEmailSendTime: RestAttribute<Email_Select>;
    DeliveryAttempts: RestAttribute<Email_Select>;
    DeliveryPriorityCode: RestAttribute<Email_Select>;
    DeliveryReceiptRequested: RestAttribute<Email_Select>;
    Description: RestAttribute<Email_Select>;
    DirectionCode: RestAttribute<Email_Select>;
    EmailReminderExpiryTime: RestAttribute<Email_Select>;
    EmailReminderStatus: RestAttribute<Email_Select>;
    EmailReminderText: RestAttribute<Email_Select>;
    EmailReminderType: RestAttribute<Email_Select>;
    EmailSender: RestAttribute<Email_Select>;
    EmailTrackingId: RestAttribute<Email_Select>;
    ExchangeRate: RestAttribute<Email_Select>;
    FollowEmailUserPreference: RestAttribute<Email_Select>;
    ImportSequenceNumber: RestAttribute<Email_Select>;
    InReplyTo: RestAttribute<Email_Select>;
    IsBilled: RestAttribute<Email_Select>;
    IsEmailFollowed: RestAttribute<Email_Select>;
    IsEmailReminderSet: RestAttribute<Email_Select>;
    IsRegularActivity: RestAttribute<Email_Select>;
    IsUnsafe: RestAttribute<Email_Select>;
    IsWorkflowCreated: RestAttribute<Email_Select>;
    LastOnHoldTime: RestAttribute<Email_Select>;
    LastOpenedTime: RestAttribute<Email_Select>;
    LinksClickedCount: RestAttribute<Email_Select>;
    MessageId: RestAttribute<Email_Select>;
    MessageIdDupCheck: RestAttribute<Email_Select>;
    MimeType: RestAttribute<Email_Select>;
    ModifiedBy: RestAttribute<Email_Select>;
    ModifiedOn: RestAttribute<Email_Select>;
    ModifiedOnBehalfBy: RestAttribute<Email_Select>;
    Notifications: RestAttribute<Email_Select>;
    OnHoldTime: RestAttribute<Email_Select>;
    OpenCount: RestAttribute<Email_Select>;
    OverriddenCreatedOn: RestAttribute<Email_Select>;
    OwnerId: RestAttribute<Email_Select>;
    OwningBusinessUnit: RestAttribute<Email_Select>;
    OwningTeam: RestAttribute<Email_Select>;
    OwningUser: RestAttribute<Email_Select>;
    ParentActivityId: RestAttribute<Email_Select>;
    PostponeEmailProcessingUntil: RestAttribute<Email_Select>;
    PriorityCode: RestAttribute<Email_Select>;
    ProcessId: RestAttribute<Email_Select>;
    ReadReceiptRequested: RestAttribute<Email_Select>;
    RegardingObjectId: RestAttribute<Email_Select>;
    ReminderActionCardId: RestAttribute<Email_Select>;
    ReplyCount: RestAttribute<Email_Select>;
    SLAId: RestAttribute<Email_Select>;
    SLAInvokedId: RestAttribute<Email_Select>;
    ScheduledDurationMinutes: RestAttribute<Email_Select>;
    ScheduledEnd: RestAttribute<Email_Select>;
    ScheduledStart: RestAttribute<Email_Select>;
    Sender: RestAttribute<Email_Select>;
    SenderMailboxId: RestAttribute<Email_Select>;
    SendersAccount: RestAttribute<Email_Select>;
    SentOn: RestAttribute<Email_Select>;
    SortDate: RestAttribute<Email_Select>;
    StageId: RestAttribute<Email_Select>;
    StateCode: RestAttribute<Email_Select>;
    StatusCode: RestAttribute<Email_Select>;
    Subcategory: RestAttribute<Email_Select>;
    Subject: RestAttribute<Email_Select>;
    SubmittedBy: RestAttribute<Email_Select>;
    TemplateId: RestAttribute<Email_Select>;
    TimeZoneRuleVersionNumber: RestAttribute<Email_Select>;
    ToRecipients: RestAttribute<Email_Select>;
    TrackingToken: RestAttribute<Email_Select>;
    TransactionCurrencyId: RestAttribute<Email_Select>;
    TraversedPath: RestAttribute<Email_Select>;
    UTCConversionTimeZoneCode: RestAttribute<Email_Select>;
    VersionNumber: RestAttribute<Email_Select>;
    bcc: RestAttribute<Email_Select>;
    cc: RestAttribute<Email_Select>;
    from: RestAttribute<Email_Select>;
    to: RestAttribute<Email_Select>;
  }
  interface Email_Filter {
    ActivityAdditionalParams: string;
    ActivityId: XQR.Guid;
    ActivityTypeCode: string;
    ActualDurationMinutes: number;
    ActualEnd: Date;
    ActualStart: Date;
    AttachmentCount: number;
    AttachmentOpenCount: number;
    BaseConversationIndexHash: number;
    Category: string;
    Compressed: boolean;
    ConversationIndex: string;
    ConversationTrackingId: XQR.Guid;
    CorrelationMethod: XQR.ValueContainerFilter<email_correlationmethod>;
    CreatedBy: XQR.EntityReferenceFilter;
    CreatedOn: Date;
    CreatedOnBehalfBy: XQR.EntityReferenceFilter;
    DelayedEmailSendTime: Date;
    DeliveryAttempts: number;
    DeliveryPriorityCode: XQR.ValueContainerFilter<activitypointer_deliveryprioritycode>;
    DeliveryReceiptRequested: boolean;
    Description: string;
    DirectionCode: boolean;
    EmailReminderExpiryTime: Date;
    EmailReminderStatus: XQR.ValueContainerFilter<email_reminderstatus>;
    EmailReminderText: string;
    EmailReminderType: XQR.ValueContainerFilter<email_remindertype>;
    EmailSender: XQR.EntityReferenceFilter;
    EmailTrackingId: XQR.Guid;
    ExchangeRate: any;
    FollowEmailUserPreference: boolean;
    ImportSequenceNumber: number;
    InReplyTo: string;
    IsBilled: boolean;
    IsEmailFollowed: boolean;
    IsEmailReminderSet: boolean;
    IsRegularActivity: boolean;
    IsUnsafe: number;
    IsWorkflowCreated: boolean;
    LastOnHoldTime: Date;
    LastOpenedTime: Date;
    LinksClickedCount: number;
    MessageId: string;
    MessageIdDupCheck: XQR.Guid;
    MimeType: string;
    ModifiedBy: XQR.EntityReferenceFilter;
    ModifiedOn: Date;
    ModifiedOnBehalfBy: XQR.EntityReferenceFilter;
    Notifications: XQR.ValueContainerFilter<email_notifications>;
    OnHoldTime: number;
    OpenCount: number;
    OverriddenCreatedOn: Date;
    OwnerId: XQR.EntityReferenceFilter;
    OwningBusinessUnit: XQR.EntityReferenceFilter;
    OwningTeam: XQR.EntityReferenceFilter;
    OwningUser: XQR.EntityReferenceFilter;
    ParentActivityId: XQR.EntityReferenceFilter;
    PostponeEmailProcessingUntil: Date;
    PriorityCode: XQR.ValueContainerFilter<email_prioritycode>;
    ProcessId: XQR.Guid;
    ReadReceiptRequested: boolean;
    RegardingObjectId: XQR.EntityReferenceFilter;
    ReminderActionCardId: XQR.Guid;
    ReplyCount: number;
    SLAId: XQR.EntityReferenceFilter;
    SLAInvokedId: XQR.EntityReferenceFilter;
    ScheduledDurationMinutes: number;
    ScheduledEnd: Date;
    ScheduledStart: Date;
    Sender: string;
    SenderMailboxId: XQR.EntityReferenceFilter;
    SendersAccount: XQR.EntityReferenceFilter;
    SentOn: Date;
    SortDate: Date;
    StageId: XQR.Guid;
    StateCode: XQR.ValueContainerFilter<email_statecode>;
    StatusCode: XQR.ValueContainerFilter<email_statuscode>;
    Subcategory: string;
    Subject: string;
    SubmittedBy: string;
    TemplateId: XQR.EntityReferenceFilter;
    TimeZoneRuleVersionNumber: number;
    ToRecipients: string;
    TrackingToken: string;
    TransactionCurrencyId: XQR.EntityReferenceFilter;
    TraversedPath: string;
    UTCConversionTimeZoneCode: number;
    VersionNumber: number;
    bcc: XQR.EntityReferenceFilter;
    cc: XQR.EntityReferenceFilter;
    from: XQR.EntityReferenceFilter;
    to: XQR.EntityReferenceFilter;
  }
  interface Email_Expand {
    Account_Email_EmailSender: RestExpand<Email_Select, Account_Select>;
    Account_Email_SendersAccount: RestExpand<Email_Select, Account_Select>;
    Account_Emails: RestExpand<Email_Select, Account_Select>;
    Contact_Email_EmailSender: RestExpand<Email_Select, Contact_Select>;
    Contact_Emails: RestExpand<Email_Select, Contact_Select>;
    Referencedemail_email_parentactivityid: RestExpand<Email_Select, Email_Select>;
    Referencingemail_email_parentactivityid: RestExpand<Email_Select, Email_Select>;
    SystemUser_Email_EmailSender: RestExpand<Email_Select, SystemUser_Select>;
    activity_pointer_email: RestExpand<Email_Select, ActivityPointer_Select>;
    email_activity_parties: RestExpand<Email_Select, ActivityParty_Select>;
    email_connections1: RestExpand<Email_Select, Connection_Select>;
    email_connections2: RestExpand<Email_Select, Connection_Select>;
    lk_email_createdby: RestExpand<Email_Select, SystemUser_Select>;
    lk_email_createdonbehalfby: RestExpand<Email_Select, SystemUser_Select>;
    lk_email_modifiedby: RestExpand<Email_Select, SystemUser_Select>;
    lk_email_modifiedonbehalfby: RestExpand<Email_Select, SystemUser_Select>;
    user_email: RestExpand<Email_Select, SystemUser_Select>;
  }
}
interface RestEntities {
  Email: RestMapping<Rest.Email,Rest.Email_Select,Rest.Email_Expand,Rest.Email_Filter,Rest.EmailResult>;
}
