declare const enum systemuser_caltype {
  Professional = 0,
  Administrative = 1,
  Basic = 2,
  DeviceProfessional = 3,
  DeviceBasic = 4,
  Essential = 5,
  DeviceEssential = 6,
  Enterprise = 7,
  DeviceEnterprise = 8,
  Sales = 9,
  Service = 10,
  FieldService = 11,
  ProjectService = 12,
}
